import { NextResponse } from "next/server";
import { prisma } from "@/lib/database/client";
import { resolveRequestIdentity } from "@/lib/foundation/request-auth";
import { effectivePermissions } from "@/lib/foundation/authorization-service";
import { apiFailure } from "@/lib/foundation/api-response";
import { REPORT_CATALOG,toCsv,printableReport,pdfReport } from "@/lib/phase-10/reporting-engine";
import { recordAudit } from "@/lib/foundation/audit-service";
import { getDashboard } from "@/lib/phase-10/dashboard-service";
import type { AnalyticsPortal } from "@/lib/phase-10/scope";
function portalFor(p:Set<string>):AnalyticsPortal{if(p.has("system:super_admin")||p.has("portal:admin"))return"founder-admin";if(p.has("portal:accounts"))return"accounts";if(p.has("portal:sales_manager"))return"sales-manager";if(p.has("portal:sales_executive"))return"sales-executive";if(p.has("portal:distributor"))return"distributor";return"super-stockist";}
export async function GET(request:Request){try{const{user}=await resolveRequestIdentity(),url=new URL(request.url),code=url.searchParams.get("code")??"",format=(url.searchParams.get("format")??"CSV").toUpperCase();if(!(code in REPORT_CATALOG)||!["CSV","PRINT","PDF"].includes(format))return NextResponse.json({error:{code:"UNKNOWN_REPORT_OR_FORMAT"}},{status:400});const permissions=await effectivePermissions(prisma,user.id);if(!["portal:admin","portal:accounts","portal:sales_manager","portal:sales_executive","portal:distributor","portal:super_stockist","system:super_admin"].some(p=>permissions.has(p)))return NextResponse.json({error:{code:"REPORT_ACCESS_DENIED"}},{status:403});const dashboard=await getDashboard(prisma,user.id,portalFor(permissions),"FINANCIAL_YEAR"),rows=dashboard.months.map(m=>({month:m.month,bookedSales:m.values.booked,deliveredSales:m.values.netDelivered})),headers=["month","bookedSales","deliveredSales"];await prisma.seeraReportExport.create({data:{actorId:user.id,reportCode:code,format:format as "CSV"|"PRINT"|"PDF",filters:Object.fromEntries(url.searchParams),scopeSnapshot:{userId:user.id,portal:dashboard.portal,employeeCount:dashboard.scope.employeeCount,partyCount:dashboard.scope.partyCount},rowCount:rows.length,sensitive:(REPORT_CATALOG as Record<string,string>)[code]==="FINANCE"}});await recordAudit(prisma,{actorId:user.id,action:"report.exported",entityType:"SeeraReport",entityId:code,details:{format,rowCount:rows.length}});if(format==="PRINT")return new NextResponse(printableReport(code,headers,rows),{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"private, no-store"}});if(format==="PDF")return new NextResponse(Buffer.from(await pdfReport(code,headers,rows)),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="${code.toLowerCase()}.pdf"`,"Cache-Control":"private, no-store"}});return new NextResponse(toCsv(rows,headers),{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="${code.toLowerCase()}.csv"`,"Cache-Control":"private, no-store"}});}catch(error){return apiFailure(error,request);}}
