import Link from "next/link";
import {requireAnyPermission} from "@/lib/sales/authorization";
import {PERMISSIONS} from "@/lib/sales/constants";
import {listQuotations} from "@/lib/quotation/repository";
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){await requireAnyPermission(PERMISSIONS.QUOTATIONS_VIEW_ALL,PERMISSIONS.QUOTATIONS_VIEW_ASSIGNED,PERMISSIONS.QUOTATIONS_VIEW_SUPPORT);const p=await searchParams;
 const result=await listQuotations({q:p.q,page:Number(p.page)||1,status:p.status,approvalState:p.approval,pricingPolicy:p.policy,sort:p.sort});const qs=new URLSearchParams(Object.entries(p).filter((e):e is[string,string]=>!!e[1]));
 const href=(page:number)=>{qs.set("page",String(page));return`/sales/quotations?${qs}`};return <section className="space-y-5 text-white"><header className="flex justify-between"><div><h1 className="text-3xl font-semibold">Quotation Management</h1><p className="text-zinc-400">{result.total} authorized quotations</p></div><div className="flex gap-2"><Link href="/sales/quotations/new" className="rounded-xl bg-amber-400 px-4 py-2 text-black">New quotation</Link><Link href="/sales/quotations/approvals" className="rounded-xl border px-4 py-2">Approval queue</Link><a href={`/api/sales/quotations/export?${qs}`} className="rounded-xl border px-4 py-2">Export</a></div></header>
 <form className="grid gap-3 md:grid-cols-5"><input name="q" defaultValue={p.q} placeholder="Number, customer, opportunity, GST…" className="md:col-span-2 rounded-xl bg-white/5 p-3"/><select name="status" defaultValue={p.status??""} className="rounded-xl bg-zinc-900 p-3"><option value="">All statuses</option>{["DRAFT","PENDING_APPROVAL","APPROVED","SENT","VIEWED","ACCEPTED","REJECTED","EXPIRED","CANCELLED"].map(x=><option key={x}>{x}</option>)}</select><select name="policy" defaultValue={p.policy??""} className="rounded-xl bg-zinc-900 p-3"><option value="">All policies</option>{["RETAIL","DEALER","DISTRIBUTOR","INSTITUTIONAL","CORPORATE","FRANCHISE"].map(x=><option key={x}>{x}</option>)}</select><button className="rounded-xl bg-amber-400 text-black">Search</button></form>
 <div className="overflow-x-auto rounded-2xl border border-white/10"><table className="w-full text-left text-sm"><thead><tr>{["Quotation","Customer","Opportunity","Owner","Version","Status","Policy","Value","Validity"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{result.items.map(q=>{const v=q.versions[0];return <tr key={q.id} className="border-t border-white/10"><td className="p-3"><Link href={`/sales/quotations/${q.id}`} className="text-amber-400">{q.quotationNumber}</Link></td><td>{q.customer.businessName??q.customer.name}</td><td>{q.opportunity.opportunityNumber}</td><td>{q.owner.name}</td><td>v{v?.versionNumber}</td><td>{v?.status.name}</td><td>{v?.pricingPolicy.name}</td><td>{v?.grandTotal.toString()}</td><td>{v?.validUntil.toLocaleDateString()}</td></tr>})}</tbody></table></div>
 <nav className="flex justify-between">{result.page>1?<Link href={href(result.page-1)}>Previous</Link>:<span/>}<span>Page {result.page} of {result.pages}</span>{result.page<result.pages?<Link href={href(result.page+1)}>Next</Link>:<span/>}</nav></section>}
