import {readFileSync} from "node:fs";import {describe,expect,it} from "vitest";
const read=(file:string)=>readFileSync(file,"utf8");
describe("integrated product controls",()=>{
  it("does not allow a Super Stockist to self-select verified advance",()=>{const ui=read("components/seera/product/DistributionActions.tsx"),service=read("lib/sales-distribution/workflow-service.ts");expect(ui).not.toContain('name="paymentProofStatus"');expect(ui).toContain("Create payment-pending order");expect(service).toContain('status: "SUBMITTED"');expect(service).toContain("financialAcceptance: false");});
  it("requires independent Accounts review before confirming company order",()=>{const service=read("lib/sales-distribution/operational-service.ts");expect(service).toContain("PAYMENT_PROOF_SELF_REVIEW_DENIED");expect(service).toContain("ADVANCE_PAYMENT_INSUFFICIENT");expect(service).toContain('status: "CONFIRMED", financialAcceptance: true');});
  it("protects every new mutating API with the common middleware",()=>{const middleware=read("middleware.ts");for(const route of ["/api/approvals/:path*","/api/distribution/:path*","/api/field/:path*","/api/retailer/:path*","/api/travel/:path*"])expect(middleware).toContain(route);});
  it("provides partner payment and claim submission without manual internal IDs",()=>{const ui=read("components/seera/product/PartnerFinanceActions.tsx");expect(ui).toContain("Business party");expect(ui).toContain("Bank / UTR reference");expect(ui).toContain("Submit a new claim");expect(ui).not.toContain("Partner ID");});
  it("binds financial approval identity to the authenticated actor",()=>{const finance=read("lib/sales-distribution/financial-service.ts"),travel=read("lib/sales-distribution/travel-lifecycle-service.ts");expect(finance).toContain("APPROVER_IDENTITY_MISMATCH");expect(finance).toContain("LEDGER_SELF_REVERSAL_DENIED");expect(finance).toContain("CLAIM_SELF_SETTLEMENT_DENIED");expect(travel).toContain("APPROVER_IDENTITY_MISMATCH");});
  // Was asserting the literal text of a permission-Set-scanning implementation that had a real P0
  // bug: a user holding two roles whose permissions granted different portal:* values always landed
  // on whichever portal was checked first, regardless of which role was actually "primary" for that
  // person (Founder UAT finding — a SALES_MANAGER-only user ended up in /portal/accounts after a
  // second role was assigned). portal-landing.ts now derives the landing portal from a single
  // "primary role" (oldest active UserRoleAssignment) instead, so this asserts the new role->portal
  // mapping keeps Founder and Company Admin on their own separate shells, which is the actual
  // invariant this test exists to protect — not the old scanning mechanism itself.
  it("keeps Company Admin out of the Founder route shell",()=>{const landing=read("lib/foundation/portal-landing.ts");expect(landing).toContain('FOUNDER_SUPER_ADMIN: "/portal/founder-admin"');expect(landing).toContain('COMPANY_ADMIN: "/portal/company-admin"');});
  it("enforces multi-line Executive orders and prohibits Executive cash",()=>{const ui=read("components/seera/product/FieldJourney.tsx"),service=read("lib/sales-distribution/operational-service.ts");expect(ui).toContain("orderLines.map");expect(ui).toContain("+ Add product");expect(ui).not.toContain("<option>CASH</option>");expect(service).toContain("EXECUTIVE_CASH_PROHIBITED");expect(service).toContain("PAYMENT_REFERENCE_REQUIRED");});
  it("exposes scoped owner quotation and billing workspaces",()=>{const surface=read("lib/foundation/product-surface.ts"),route=read("app/api/documents/issue/route.ts"),service=read("lib/sales-distribution/document-service.ts");expect(surface).toContain('"quotations"');expect(surface).toContain('"billing"');expect(surface).toContain('"retailers"');expect(surface).toContain('"distributors"');expect(route).toContain("QUOTATION_DOCUMENT");expect(service).toContain("DOCUMENT_ISSUER_SCOPE_DENIED");});
  it("provides manager beat planning with human selectors and team scope enforcement",()=>{const surface=read("lib/foundation/product-surface.ts"),ui=read("components/seera/product/BeatPlannerActions.tsx"),service=read("lib/sales-distribution/operational-service.ts");expect(surface).toContain('"beat-planner"');expect(ui).toContain('action: "publish-plan"');expect(ui).toContain('name="employeeId"');expect(ui).toContain('name="geographyName"');expect(service).toContain("EXECUTIVE_SCOPE_DENIED");expect(service).toContain("journey_plan.published");});
  it("uses governed multi-line products for both replenishment paths",()=>{const ui=read("components/seera/product/DistributionActions.tsx"),service=read("lib/sales-distribution/workflow-service.ts");expect(ui).toContain("orderLines.map");expect(ui).toContain('"company-order"');expect(ui).not.toContain('name="subtotal"');expect(service).toContain('tier:"COMPANY_TO_SS"');expect(service).toContain('lines:{create:snapshots.map');});
  // Distributor Easy Mode (later pass) replaced the old literal `<DistributionActions kind="allocate">`
  // / `kind="dispatch"` Distributor screens with SuperStockistOrderCards/DistributorOrderCards, whose
  // ACCEPT auto-allocates via acceptAndPrepareRetailerOrder/acceptAndAllocateDistributorOrder instead
  // of a manual separate step — the underlying allocation/dispatch/delivery capability this test
  // guards is unchanged, only how it's reached from the UI. The Super Stockist portal still exposes
  // the advanced allocate/dispatch screens directly (kind is chosen dynamically by nav slug there).
  it("wires allocation, dispatch and scoped delivery execution",()=>{const workspace=read("components/seera/product/OperationalWorkspace.tsx"),service=read("lib/sales-distribution/workflow-service.ts"),delivery=read("lib/sales-distribution/delivery-service.ts"),easyMode=read("lib/sales-distribution/distributor-easy-mode-service.ts");expect(workspace).toContain('kind={item.slug==="allocation"?"allocate":"dispatch"}');expect(workspace).toContain("SuperStockistOrderCards");expect(workspace).toContain("DistributorOrderCards");expect(workspace).toContain("<DeliveryActions");expect(service).toContain("INSUFFICIENT_AVAILABLE_STOCK");expect(service).toContain("dispatchAllocatedOrder");expect(easyMode).toContain("allocateOrderStock");expect(easyMode).toContain("dispatchAllocatedOrder");expect(delivery).toContain("DELIVERY_REASON_REQUIRED");});
  it("drives the live replenishment credit gate off the same canonical exposure the Credit pages read",()=>{const credit=read("lib/sales-distribution/credit-service.ts"),workflow=read("lib/sales-distribution/workflow-service.ts"),rules=read("lib/sales-distribution/business-rules.ts");expect(credit).toContain("export async function canonicalDistributorExposure");expect(workflow).toContain("canonicalDistributorExposure(");expect(workflow).not.toContain("_sum: { total: true }");expect(rules).toContain("export function netCreditExposure");});
  it("never lets a Super Stockist approve their own requested credit extension",()=>{const credit=read("lib/sales-distribution/credit-service.ts");expect(credit).toContain("CREDIT_EXTENSION_SELF_APPROVAL_DENIED");expect(credit).toContain("APPROVER_IDENTITY_MISMATCH");expect(credit).toContain("CREDIT_EXTENSION_ALREADY_DECIDED");expect(credit).toContain("credit_extension:request");expect(credit).toContain("credit_extension:approve");});
  it("preserves the original due date when requesting a credit extension",()=>{const credit=read("lib/sales-distribution/credit-service.ts");expect(credit).toContain("originalDueDate: order.originalDueDate!");expect(credit).toContain("EXTENSION_BEFORE_DUE_DATE");expect(credit).not.toMatch(/order\.originalDueDate\s*=/);});
  it("gives a refused delivery a real inventory consequence and a damaged one a claim, not a silent gap",()=>{const delivery=read("lib/sales-distribution/delivery-service.ts");expect(delivery).toContain('type: "RETURN"');expect(delivery).toContain('direction: "IN"');expect(delivery).toContain("DAMAGE_IN_TRANSIT");expect(delivery).toContain("returnedQuantity");expect(delivery).toContain('"DELIVERED", "PARTIAL_DELIVERED", "REFUSED", "DAMAGED"');});
});
