import {readFileSync} from "node:fs";import {describe,expect,it} from "vitest";
const read=(file:string)=>readFileSync(file,"utf8");
describe("integrated product controls",()=>{
  it("does not allow a Super Stockist to self-select verified advance",()=>{const ui=read("components/seera/product/DistributionActions.tsx"),service=read("lib/sales-distribution/workflow-service.ts");expect(ui).not.toContain('name="paymentProofStatus"');expect(ui).toContain("Create payment-pending order");expect(service).toContain('status: "SUBMITTED"');expect(service).toContain("financialAcceptance: false");});
  it("requires independent Accounts review before confirming company order",()=>{const service=read("lib/sales-distribution/operational-service.ts");expect(service).toContain("PAYMENT_PROOF_SELF_REVIEW_DENIED");expect(service).toContain("ADVANCE_PAYMENT_INSUFFICIENT");expect(service).toContain('status: "CONFIRMED", financialAcceptance: true');});
  it("protects every new mutating API with the common middleware",()=>{const middleware=read("middleware.ts");for(const route of ["/api/approvals/:path*","/api/distribution/:path*","/api/field/:path*","/api/retailer/:path*","/api/travel/:path*"])expect(middleware).toContain(route);});
  it("provides partner payment and claim submission without manual internal IDs",()=>{const ui=read("components/seera/product/PartnerFinanceActions.tsx");expect(ui).toContain("Business party");expect(ui).toContain("Bank / UTR reference");expect(ui).toContain("Submit a new claim");expect(ui).not.toContain("Partner ID");});
  it("binds financial approval identity to the authenticated actor",()=>{const finance=read("lib/sales-distribution/financial-service.ts"),travel=read("lib/sales-distribution/travel-lifecycle-service.ts");expect(finance).toContain("APPROVER_IDENTITY_MISMATCH");expect(finance).toContain("LEDGER_SELF_REVERSAL_DENIED");expect(finance).toContain("CLAIM_SELF_SETTLEMENT_DENIED");expect(travel).toContain("APPROVER_IDENTITY_MISMATCH");});
  it("keeps Company Admin out of the Founder route shell",()=>{const landing=read("lib/foundation/portal-landing.ts");expect(landing).toContain('permissions.has("system:super_admin"))return "/portal/founder-admin"');expect(landing).toContain('permissions.has("portal:admin"))return "/portal/company-admin"');});
});
