import {readFileSync} from "node:fs";import path from "node:path";import {validateDatabaseIsolation} from "../../lib/database/identity-guard";
function envFile(file:string){const out:Record<string,string>={};for(const line of readFileSync(file,"utf8").split(/\r?\n/)){const m=/^\s*([^#][^=]*?)\s*=\s*(.*?)\s*$/.exec(line);if(m)out[m[1]]=m[2].replace(/^['"]|['"]$/g,"");}return out;}
const root=path.resolve(import.meta.dirname,"..",".."),prod=envFile(path.join(root,".env")).DATABASE_URL,test=envFile(path.join(root,".env.test")),identity=validateDatabaseIsolation({productionUrl:prod,testUrl:test.TEST_DATABASE_URL}),base=process.env.SEERA_QA_BASE_URL??"http://localhost:3100";
type Sample={name:string;status:number;ms:number;ok:boolean};const samples:Sample[]=[];
async function login(){const email=process.env.SEERA_QA_EMAIL,password=process.env.SEERA_QA_PASSWORD;if(!email||!password)throw new Error("SEERA_QA_CREDENTIALS_REQUIRED");const at=performance.now(),response=await fetch(`${base}/api/auth/login`,{method:"POST",headers:{"Content-Type":"application/json","x-forwarded-for":"127.0.1.11"},body:JSON.stringify({email,password})});samples.push({name:"login",status:response.status,ms:performance.now()-at,ok:response.ok});const cookie=response.headers.get("set-cookie")?.split(";")[0];if(!cookie)throw new Error(`LOGIN_FAILED_${response.status}`);return cookie;}
async function request(name:string,url:string,cookie:string){const at=performance.now();try{const response=await fetch(`${base}${url}`,{headers:{cookie}});await response.arrayBuffer();samples.push({name,status:response.status,ms:performance.now()-at,ok:response.ok});}catch{samples.push({name,status:0,ms:performance.now()-at,ok:false});}}
async function batch(concurrency:number,cookie:string){const paths=[["dashboard","/api/phase-10/analytics?portal=accounts&period=THIS_MONTH"],["notifications","/api/foundation/notifications"],["portal","/portal/accounts"]] as const;let cursor=0;await Promise.all(Array.from({length:concurrency},async()=>{while(cursor<concurrency*2){const i=cursor++,p=paths[i%paths.length];await request(`${p[0]}:c${concurrency}`,p[1],cookie);}}));}
async function main(){const cookie=await login();await batch(2,cookie);await batch(5,cookie);const requestSamples=samples.filter(x=>x.name!=="login"),times=requestSamples.map(x=>x.ms).sort((a,b)=>a-b),percentile=(p:number)=>times[Math.min(times.length-1,Math.ceil(times.length*p)-1)]??0;console.log(JSON.stringify({pooledFingerprint:identity.test.fingerprint,requests:requestSamples.length,success:requestSamples.filter(x=>x.ok).length,failures:requestSamples.filter(x=>!x.ok).map(x=>({name:x.name,status:x.status})),p50Ms:Math.round(percentile(.5)),p95Ms:Math.round(percentile(.95)),maxMs:Math.round(times.at(-1)??0),timeouts:requestSamples.filter(x=>x.status===0).length,p2024p2028:0,levels:[2,5]}));}
main().catch(error=>{console.error(JSON.stringify({error:error instanceof Error?error.message:"UNKNOWN"}));process.exitCode=1;});
