import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { authorize,effectivePermissions } from "@/lib/foundation/authorization-service";
import { login,resolveSession } from "@/lib/foundation/auth-service";
import { setFeatureFlag,updateSetting } from "@/lib/foundation/configuration-service";
import { getFileMetadata,registerFileMetadata } from "@/lib/foundation/file-service";
import { createNotification,listNotifications,markNotificationRead } from "@/lib/foundation/notification-service";
import { PHASE_1_PERMISSIONS } from "@/lib/foundation/rbac-catalog";
import { assignRole,createUser,removeRole,setUserStatus } from "@/lib/foundation/user-management-service";
import { expectCode,founderEmail,founderId as contextFounder,founderPassword,password,prisma,roleUsers,setup } from "./test-context";
let founderId="";
beforeAll(async()=>{await setup();founderId=(await prisma.user.findUniqueOrThrow({where:{normalizedEmail:founderEmail}})).id;});afterAll(()=>prisma.$disconnect());
describe("RBAC boundaries",()=>{
 it("seeds exactly 14 roles and 30 permissions",async()=>{expect(await prisma.role.count()).toBe(14);expect(await prisma.permission.count()).toBe(PHASE_1_PERMISSIONS.length);});
 it("Founder has all portal authority",async()=>{for(const permission of ["portal:admin","portal:accounts","portal:sales_manager","portal:sales_executive","portal:distributor","portal:super_stockist","portal:retailer"] as const)await expect(authorize(prisma,{actorId:founderId,permission})).resolves.toBeTruthy();});
 it("Company Admin lacks super-admin bypass",async()=>{const u=roleUsers.get("COMPANY_ADMIN")!;await expect(authorize(prisma,{actorId:u.id,permission:"portal:admin"})).resolves.toBeTruthy();expect((await effectivePermissions(prisma,u.id)).has("system:super_admin")).toBe(false);});
 it("Accounts, manager, executive portals are isolated",async()=>{const a=roleUsers.get("ACCOUNTS_MANAGER")!,m=roleUsers.get("SALES_MANAGER")!,e=roleUsers.get("SALES_EXECUTIVE")!;await expect(authorize(prisma,{actorId:a.id,permission:"portal:accounts"})).resolves.toBeTruthy();await expectCode(()=>authorize(prisma,{actorId:a.id,permission:"portal:admin"}),"ACCESS_DENIED");await expect(authorize(prisma,{actorId:m.id,permission:"portal:sales_manager"})).resolves.toBeTruthy();await expectCode(()=>authorize(prisma,{actorId:e.id,permission:"portal:sales_manager"}),"ACCESS_DENIED");});
 it("Distributor, SS, and Retailer cannot cross portals",async()=>{const d=roleUsers.get("DISTRIBUTOR_OWNER")!,s=roleUsers.get("SUPER_STOCKIST_OWNER")!,r=roleUsers.get("RETAILER_USER")!;await expectCode(()=>authorize(prisma,{actorId:d.id,permission:"portal:super_stockist"}),"ACCESS_DENIED");await expectCode(()=>authorize(prisma,{actorId:s.id,permission:"portal:distributor"}),"ACCESS_DENIED");await expectCode(()=>authorize(prisma,{actorId:r.id,permission:"portal:admin"}),"ACCESS_DENIED");});
 it("Auditor reads but cannot mutate",async()=>{const u=roleUsers.get("READ_ONLY_AUDITOR")!;await expect(authorize(prisma,{actorId:u.id,permission:"audit:view"})).resolves.toBeTruthy();await expectCode(()=>authorize(prisma,{actorId:u.id,permission:"settings:manage"}),"ACCESS_DENIED");});
});
describe("Admin lifecycle and privilege controls",()=>{
 let targetId="",targetEmail="",targetPassword="";
 it("creates users and rejects duplicate identity",async()=>{targetEmail=`managed-${Date.now()}@example.test`;targetPassword=password();targetId=(await createUser(prisma,founderId,{email:targetEmail,name:"Managed",password:targetPassword})).id;await expect(createUser(prisma,founderId,{email:targetEmail,name:"Duplicate",password:targetPassword})).rejects.toBeTruthy();});
 it("supports multiple roles and blocks duplicates",async()=>{await assignRole(prisma,founderId,targetId,"SALES_EXECUTIVE","test");await assignRole(prisma,founderId,targetId,"RETAILER_USER","test");expect((await effectivePermissions(prisma,targetId)).has("portal:retailer")).toBe(true);await expectCode(()=>assignRole(prisma,founderId,targetId,"RETAILER_USER","duplicate"),"DUPLICATE_ROLE_ASSIGNMENT");});
 it("role removal immediately stales sessions",async()=>{const session=await login(prisma,{email:targetEmail,password:targetPassword});await removeRole(prisma,founderId,targetId,"RETAILER_USER","test");await expectCode(()=>resolveSession(prisma,session.token),"SESSION_INVALID");expect((await effectivePermissions(prisma,targetId)).has("portal:retailer")).toBe(false);});
 it("suspend, disable, and reactivate are enforced",async()=>{for(const state of ["SUSPENDED","DISABLED"] as const){await setUserStatus(prisma,founderId,targetId,state,"test");await expectCode(()=>login(prisma,{email:targetEmail,password:targetPassword}),"USER_ACCESS_DISABLED");await setUserStatus(prisma,founderId,targetId,"ACTIVE","reactivate");}});
 it("blocks self-promotion and last-Founder removal",async()=>{const admin=roleUsers.get("COMPANY_ADMIN")!;await expectCode(()=>assignRole(prisma,admin.id,admin.id,"FOUNDER_SUPER_ADMIN","forged"),"SYSTEM_ROLE_ASSIGNMENT_DENIED");await expectCode(()=>removeRole(prisma,founderId,founderId,"FOUNDER_SUPER_ADMIN","forged"),"LAST_FOUNDER_PROTECTED");await expectCode(()=>setUserStatus(prisma,founderId,founderId,"DISABLED","forged"),"SELF_LOCKOUT_DENIED");});
});
describe("Flags, settings, notifications, files, and audit",()=>{
 it("feature flag never overrides RBAC",async()=>{const accounts=roleUsers.get("ACCOUNTS_MANAGER")!,retailer=roleUsers.get("RETAILER_USER")!;await setFeatureFlag(prisma,founderId,"portal.accounts.enabled",true,"test");await expect(authorize(prisma,{actorId:accounts.id,permission:"portal:accounts",featureFlag:"portal.accounts.enabled"})).resolves.toBeTruthy();await expectCode(()=>authorize(prisma,{actorId:retailer.id,permission:"portal:accounts",featureFlag:"portal.accounts.enabled"}),"ACCESS_DENIED");await setFeatureFlag(prisma,founderId,"portal.accounts.enabled",false,"test");await expectCode(()=>authorize(prisma,{actorId:accounts.id,permission:"portal:accounts",featureFlag:"portal.accounts.enabled"}),"PORTAL_DISABLED");await setFeatureFlag(prisma,founderId,"portal.accounts.enabled",true,"restore");});
 it("validates and audits typed settings",async()=>{await updateSetting(prisma,founderId,{key:"foundation.test",category:"test",valueType:"BOOLEAN",value:true,reason:"test"});await expect(updateSetting(prisma,founderId,{key:"foundation.test",category:"test",valueType:"BOOLEAN",value:"true",reason:"bad"})).rejects.toMatchObject({code:"SETTING_TYPE_MISMATCH"});});
 it("notification inbox is recipient-private and persists read",async()=>{const recipient=roleUsers.get("SALES_EXECUTIVE")!,other=roleUsers.get("RETAILER_USER")!;const n=await createNotification(prisma,founderId,{recipientId:recipient.id,title:"Ready",body:"Foundation"});expect((await listNotifications(prisma,recipient.id,recipient.id))[0]?.id).toBe(n.id);await expect(listNotifications(prisma,other.id,recipient.id)).rejects.toMatchObject({code:"CROSS_USER_ACCESS_DENIED"});expect((await markNotificationRead(prisma,recipient.id,n.id)).status).toBe("READ");await expect(markNotificationRead(prisma,other.id,n.id)).rejects.toMatchObject({code:"CROSS_USER_ACCESS_DENIED"});});
 it("private file metadata validates and blocks cross-user reads",async()=>{const admin=roleUsers.get("COMPANY_ADMIN")!,other=roleUsers.get("SALES_EXECUTIVE")!;const file=await registerFileMetadata(prisma,admin.id,{originalName:"evidence.pdf",mimeType:"application/pdf",sizeBytes:100n,sha256:"a".repeat(64)});expect(file.uploadedById).toBe(admin.id);expect(file.storageKey).toMatch(new RegExp(`^private/${admin.id}/`));expect(Object.keys(file)).not.toContain("publicUrl");await expect(getFileMetadata(prisma,other.id,file.id)).rejects.toMatchObject({code:"PRIVATE_FILE_ACCESS_DENIED"});await expect(registerFileMetadata(prisma,admin.id,{originalName:"../bad",mimeType:"application/pdf",sizeBytes:1n,sha256:"a".repeat(64)})).rejects.toBeTruthy();});
 it("rejects unknown settings, flags, and notification markup",async()=>{await expect(updateSetting(prisma,founderId,{key:"injected.secret",category:"bad",valueType:"STRING",value:"x",reason:"attack"})).rejects.toMatchObject({code:"UNKNOWN_SETTING_KEY"});await expect(setFeatureFlag(prisma,founderId,"portal.unknown.enabled",true,"attack")).rejects.toMatchObject({code:"UNKNOWN_FEATURE_FLAG"});await expect(createNotification(prisma,founderId,{recipientId:founderId,title:"<script>",body:"x"})).rejects.toBeTruthy();});
 it("audits critical mutations without secrets",async()=>{const actions=(await prisma.auditLog.findMany({select:{action:true}})).map(x=>x.action);for(const action of ["founder.bootstrap","user.create","user.status_change","role.assign","role.remove","session.revoke_all","settings.update","feature_flag.update"])expect(actions).toContain(action);const text=JSON.stringify(await prisma.auditLog.findMany());expect(text).not.toContain(founderPassword);expect(text).not.toMatch(/passwordHash|sessionToken|DATABASE_URL/);});
 it("security challenge denies forged actor and stale disabled identity",async()=>{const distributor=roleUsers.get("DISTRIBUTOR_OWNER")!;await expectCode(()=>authorize(prisma,{actorId:distributor.id,permission:"portal:admin"}),"ACCESS_DENIED");await prisma.user.update({where:{id:distributor.id},data:{status:"DISABLED",authorizationVersion:{increment:1}}});await expectCode(()=>authorize(prisma,{actorId:distributor.id,permission:"portal:distributor"}),"USER_ACCESS_DISABLED");});
});
