import { getAiPrincipal } from "@/lib/muv-ai/authorization";
import { requireAiAdminPermission } from "@/lib/muv-ai/security";
import { prisma } from "@/lib/prisma";

export default async function AiAdminPage(){
 const p=await getAiPrincipal();
 requireAiAdminPermission(p);
 const [prompts,agents,tools,providers,workflows,knowledge,flags]=await Promise.all([prisma.aiPromptTemplate.findMany({orderBy:[{code:"asc"},{version:"desc"}]}),prisma.aiAgentDefinition.findMany({orderBy:{name:"asc"}}),prisma.aiToolDefinition.findMany({orderBy:{name:"asc"}}),prisma.aiProvider.findMany({orderBy:{priority:"asc"}}),prisma.aiWorkflowDefinition.findMany({orderBy:{name:"asc"}}),prisma.aiKnowledgeRecord.count({where:{organizationKey:p.organizationKey,status:"PUBLISHED"}}),prisma.aiConfiguration.findMany({where:{organizationKey:p.organizationKey,category:"FEATURE_FLAG"},orderBy:{key:"asc"}})]);
 return <section className="space-y-6 text-white"><header><h1 className="text-3xl font-semibold">MUV AI Administration</h1><p className="text-sm text-zinc-400">Governed registries and feature activation. Provider secrets are never displayed.</p></header><div className="grid gap-4 md:grid-cols-4">{[["Prompts",prompts.length],["Agents",agents.length],["Tools",tools.length],["Published knowledge",knowledge]].map(([a,b])=><article key={a} className="rounded-2xl border border-white/10 p-5"><p className="text-zinc-400">{a}</p><p className="mt-2 text-3xl">{b}</p></article>)}</div><div className="grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-white/10 p-5"><h2>Feature flags</h2>{flags.map(f=><p key={f.id} className="mt-3 text-sm">{f.key}: {String((f.value as {enabled?:boolean}).enabled)}</p>)}<h2 className="mt-6">Providers</h2>{providers.map(x=><p key={x.id} className="mt-3 text-sm">{x.code} · {x.status}</p>)}</article><article className="rounded-2xl border border-white/10 p-5"><h2>Agents and tools</h2>{agents.map(x=><p key={x.id} className="mt-2 text-sm">{x.name} · {x.status}</p>)}<p className="mt-4 text-xs text-zinc-500">{tools.length} registered tools · {workflows.length} workflow definitions · {prompts.filter(x=>x.status==="PUBLISHED").length} published prompt versions</p></article></div></section>;
}
