import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/database/client";
import { resolveRequestIdentity } from "@/lib/foundation/request-auth";
import { authorize } from "@/lib/foundation/authorization-service";
import { apiFailure } from "@/lib/foundation/api-response";
import { recordAudit } from "@/lib/foundation/audit-service";
const update=z.object({id:z.string().min(1),enabled:z.boolean().optional(),cooldownMinutes:z.number().int().min(0).max(525600).optional(),timingOffsetMinutes:z.number().int().min(-525600).max(525600).optional(),severity:z.enum(["INFO","SUCCESS","WARNING","HIGH","CRITICAL"]).optional(),channels:z.array(z.enum(["IN_APP","EMAIL","WHATSAPP"])).min(1).optional()}).refine(v=>Object.keys(v).length>1,"A rule change is required");
export async function GET(request:Request){try{const{user}=await resolveRequestIdentity();await authorize(prisma,{actorId:user.id,permission:"settings:view"});return NextResponse.json({rules:await prisma.seeraAutomationRule.findMany({orderBy:{code:"asc"}})},{headers:{"Cache-Control":"private, no-store"}});}catch(error){return apiFailure(error,request);}}
export async function PATCH(request:Request){try{const{user}=await resolveRequestIdentity();await authorize(prisma,{actorId:user.id,permission:"settings:manage"});const data=update.parse(await request.json()),before=await prisma.seeraAutomationRule.findUniqueOrThrow({where:{id:data.id}}),after=await prisma.seeraAutomationRule.update({where:{id:data.id},data:{enabled:data.enabled,cooldownMinutes:data.cooldownMinutes,timingOffsetMinutes:data.timingOffsetMinutes,severity:data.severity,channels:data.channels}});await recordAudit(prisma,{actorId:user.id,action:"automation.rule.updated",entityType:"SeeraAutomationRule",entityId:after.id,beforeState:{enabled:before.enabled,cooldownMinutes:before.cooldownMinutes,timingOffsetMinutes:before.timingOffsetMinutes,severity:before.severity},afterState:{enabled:after.enabled,cooldownMinutes:after.cooldownMinutes,timingOffsetMinutes:after.timingOffsetMinutes,severity:after.severity}});return NextResponse.json({rule:after});}catch(error){return apiFailure(error,request);}}
