import { Lightbulb } from "lucide-react";

/**
 * MUV OS™ — Core Platform Foundation (Milestone 1), AI Panel Foundation.
 * Suggestions are always App-sourced and proposal-only (never
 * auto-generated by the Shell) per Manifest Architecture §6 — with zero
 * Apps registered, there is nothing to propose.
 */
export function SuggestionsTab() {
  return (
    <div className="flex flex-1 flex-col items-center justify-center gap-2 px-6 py-12 text-center">
      <Lightbulb size={22} style={{ color: "rgba(var(--text-rgb),0.3)" }} aria-hidden="true" />
      <p className="text-sm" style={{ color: "rgba(var(--text-rgb),0.55)" }}>
        No suggestions right now.
      </p>
    </div>
  );
}
