import { readFileSync } from "node:fs";import path from "node:path";import { describe,expect,it } from "vitest";
import { FoundationError,safeError } from "@/lib/foundation/errors";import { enforceRateLimit,resetRateLimitsForTests } from "@/lib/foundation/rate-limit";import { GET as live } from "@/app/api/health/live/route";import { GET as ready } from "@/app/api/health/ready/route";import { PHASE_1_FEATURE_FLAGS } from "@/lib/foundation/rbac-catalog";
const root=process.cwd(),read=(file:string)=>readFileSync(path.join(root,file),"utf8");
describe("Block 4 hardening",()=>{
 it("returns stable safe error categories without secrets",()=>{const requestId="request-123";expect(safeError(new FoundationError("ACCESS_DENIED","Access denied",403),requestId)).toEqual({status:403,body:{error:{code:"ACCESS_DENIED",message:"Access denied",requestId}}});expect(JSON.stringify(safeError(new Error("postgresql://user:password@secret/db"),requestId))).not.toContain("password");});
 it("liveness discloses no infrastructure",async()=>{const response=await live(),body=await response.text();expect(response.status).toBe(200);expect(body).not.toMatch(/postgres|neon|fingerprint|password/i);});
 it("readiness discloses no database endpoint",async()=>{const response=await ready(),body=await response.text();expect([200,503]).toContain(response.status);expect(body).not.toMatch(/neon\.tech|postgresql:\/\/|fingerprint|password/i);});
 it("rate limit fails with stable 429 after threshold",()=>{resetRateLimitsForTests();for(let i=0;i<3;i++)enforceRateLimit("test",3,1000,0);expect(()=>enforceRateLimit("test",3,1000,0)).toThrowError(expect.objectContaining({code:"RATE_LIMITED",status:429}));});
 it("declares security and private-cache headers",()=>{const config=read("next.config.ts");for(const header of ["Content-Security-Policy","X-Frame-Options","X-Content-Type-Options","Referrer-Policy","Cache-Control"])expect(config).toContain(header);expect(config).toContain("private, no-store");});
 it("keeps only the six approved portal flags",()=>{expect(PHASE_1_FEATURE_FLAGS).toHaveLength(6);expect(new Set(PHASE_1_FEATURE_FLAGS).size).toBe(6);});
 it("provides no audit update or delete endpoint",()=>{const audit=read("lib/foundation/audit-service.ts"),route=read("app/api/foundation/audit/route.ts");expect(audit).not.toMatch(/auditLog\.(update|delete)/);expect(route).not.toMatch(/export async function (POST|PATCH|DELETE)/);});
 it("keeps idempotency and outbox lifecycle/index foundations",()=>{const schema=read("prisma/schema.prisma");expect(schema).toContain("@@unique([scope, key])");expect(schema).toContain("@@index([status, lockedUntil])");expect(schema).toContain("@@index([status, availableAt])");expect(schema).toContain("attempts");});
 it("protects every active foundation API through request identity or public-health classification",()=>{const protectedRoutes=["app/api/foundation/users/route.ts","app/api/foundation/users/[id]/route.ts","app/api/foundation/notifications/route.ts","app/api/foundation/audit/route.ts","app/api/foundation/configuration/route.ts"];for(const route of protectedRoutes)expect(read(route)).toContain("resolveRequestIdentity");});
 it("preserves the Phase 1 authorization boundary while activating isolated Seera domain experiences",()=>{const schema=read("prisma/schema.prisma");for(const model of ["Product","Retailer","Distributor","SuperStockist","Beat","SalesVisit","CommercialOrder","Payment","Ledger","ExpenseClaim"])expect(schema).not.toMatch(new RegExp(`^model ${model} \\{`,"m"));const portal=read("app/portal/[portal]/page.tsx");expect(portal).toContain("resolveRequestIdentity");expect(portal).toContain("authorize");expect(portal).toContain("PORTAL_EXPERIENCES");});
});
