import {randomUUID} from "node:crypto";
import {PrismaClient,Prisma} from "@prisma/client";
import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {offlineBootstrap} from "@/lib/phase-11/offline-bootstrap-service";
import {syncOfflineOperation} from "@/lib/phase-11/offline-sync-service";

const flow=process.env.SEERA_OFFLINE_CLOSURE_FLOW;
if(flow!=="4"&&flow!=="6")throw new Error("SEERA_OFFLINE_CLOSURE_FLOW must be 4 or 6");
const correlationId=randomUUID(),suffix=correlationId.replaceAll("-","").slice(0,12);
const db=new PrismaClient({log:[{emit:"event",level:"query"},{emit:"event",level:"error"}]});
let founderId="",userId="",roleId="",permissionId="",partnerId="",retailerId="",skuId="",sessionId="";
let ownsPermission=false;
const operationIds:string[]=[];
let active=0,maxConcurrent=0;
db.$on("query",event=>console.log(JSON.stringify({correlationId,event:"query-complete",category:(/^\s*(SELECT|INSERT|UPDATE|DELETE|BEGIN|COMMIT|ROLLBACK)/i.exec(event.query)?.[1]??"OTHER").toUpperCase(),durationMs:event.duration})));
db.$on("error",event=>console.log(JSON.stringify({correlationId,event:"prisma-error",message:event.message.replace(/postgres(?:ql)?:\/\/\S+/gi,"[REDACTED_URL]")})));
async function inspect(){const inspector=new PrismaClient();try{return await inspector.$queryRaw<Array<{state:string|null;wait_event_type:string|null;wait_event:string|null;query_age_ms:number|null;idle_in_transaction:boolean}>>(Prisma.sql`SELECT state,wait_event_type,wait_event,EXTRACT(EPOCH FROM (clock_timestamp()-query_start))*1000 AS query_age_ms,(state='idle in transaction') AS idle_in_transaction FROM pg_stat_activity WHERE datname=current_database() AND pid<>pg_backend_pid() AND state IS DISTINCT FROM 'idle'`);}finally{await inspector.$disconnect();}}
async function step<T>(name:string,modelMethod:string,fn:()=>Promise<T>,timeoutMs=30_000){const started=Date.now();active++;maxConcurrent=Math.max(maxConcurrent,active);console.log(JSON.stringify({correlationId,flow,event:"operation-start",name,modelMethod,transaction:false,awaited:true}));let timer:NodeJS.Timeout|undefined;try{const result=await Promise.race([fn(),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Object.assign(new Error(`OPERATION_TIMEOUT:${name}`),{code:"OPERATION_TIMEOUT"})),timeoutMs);})]);console.log(JSON.stringify({correlationId,flow,event:"operation-finish",name,modelMethod,durationMs:Date.now()-started}));return result;}catch(error){console.log(JSON.stringify({correlationId,flow,event:"operation-failure",name,modelMethod,durationMs:Date.now()-started,code:typeof error==="object"&&error&&"code" in error?String(error.code):null,message:error instanceof Error?error.message:"UNKNOWN",activity:await inspect()}));throw error;}finally{if(timer)clearTimeout(timer);active--;}}
async function reconnect(){const started=Date.now();await db.$disconnect();const disconnectedMs=Date.now()-started,connectAt=Date.now();await db.$connect();console.log(JSON.stringify({correlationId,flow,event:"reconnect",disconnectedMs,connectedMs:Date.now()-connectAt}));}
function operation(id=randomUUID()){operationIds.push(id);return{clientOperationId:id,deviceId:`device-${suffix}`,sessionContext:{sessionId,appVersion:"phase11-closure",platform:"test"},entityType:"ORDER",actionType:"ORDER_DRAFT",localCreatedAt:new Date(),payloadVersion:1,payload:{retailerId,commercialPartyId:partnerId,lines:[{skuId,quantity:flow==="6"?3:1,priceSnapshot:80}],remarks:`offline-${flow}-${suffix}`}};}

beforeAll(async()=>{
 founderId=(await step("fixture-founder","User.create",()=>db.user.create({data:{email:`founder-${suffix}@example.test`,normalizedEmail:`founder-${suffix}@example.test`,name:"Closure Founder"}}))).id;
 userId=(await step("fixture-user","User.create",()=>db.user.create({data:{email:`executive-${suffix}@example.test`,normalizedEmail:`executive-${suffix}@example.test`,name:"Closure Executive"}}))).id;
 roleId=(await step("fixture-role","Role.create",()=>db.role.create({data:{code:`CLOSURE_EXEC_${suffix}`,name:"Closure Executive"}}))).id;
 const existingPermission=await step("fixture-permission-lookup","Permission.findUnique",()=>db.permission.findUnique({where:{code:"retailer:order"}}));
 if(existingPermission)permissionId=existingPermission.id;else{ownsPermission=true;permissionId=(await step("fixture-permission","Permission.create",()=>db.permission.create({data:{code:"retailer:order",resource:"retailer",action:"order"}}))).id;}
 await step("fixture-role-permission","RolePermission.create",()=>db.rolePermission.create({data:{roleId,permissionId}}));
 await step("fixture-assignment","UserRoleAssignment.create",()=>db.userRoleAssignment.create({data:{userId,roleId,assignedById:founderId}}));
 partnerId=(await step("fixture-partner","SeeraPartner.create",()=>db.seeraPartner.create({data:{type:"DISTRIBUTOR",code:`CLOSURE-D-${suffix}`,legalName:"Closure Distributor",lifecycle:"ACTIVE",primaryContact:{mobile:"9000000011"},addresses:{city:"Test"},territoryIds:["CLOSURE"],createdById:founderId}}))).id;
 await step("fixture-party-user","SeeraPartyUser.create",()=>db.seeraPartyUser.create({data:{partnerId,userId,accessRole:"OWNER",createdById:founderId}}));
 retailerId=(await step("fixture-retailer","SeeraRetailer.create",()=>db.seeraRetailer.create({data:{code:`CLOSURE-R-${suffix}`,businessName:"Closure Retailer",ownerName:"Owner",mobile:`92${suffix.slice(0,8)}`,normalizedMobile:`92${suffix.slice(0,8)}`,address:{city:"Test"},shopType:"GT",distributorId:partnerId,salespersonId:userId,lifecycle:"ACTIVE",createdById:founderId}}))).id;
 skuId=(await step("fixture-sku","SeeraSku.create",()=>db.seeraSku.create({data:{code:`CLOSURE-SKU-${suffix}`,productName:"Closure SKU",category:"CARE",packSize:1,unitType:"PCS",unitsPerCase:1,mrp:100,status:"ACTIVE",createdById:founderId}}))).id;
 await step("fixture-price","SeeraPriceVersion.create",()=>db.seeraPriceVersion.create({data:{skuId,tier:"DISTRIBUTOR_TO_RETAILER",amount:80,mrpSnapshot:100,effectiveFrom:new Date("2026-01-01"),status:"ACTIVE",createdById:founderId}}));
 sessionId=(await step("fixture-work-session","SeeraWorkSession.create",()=>db.seeraWorkSession.create({data:{employeeId:userId,employeeRole:"SALES_EXECUTIVE",workingType:"RETAILING",status:"ACTIVE",startedAt:new Date()}}))).id;
},120_000);

afterAll(async()=>{const started=Date.now();try{await db.seeraOfflineOperation.deleteMany({where:{userId}});await db.auditLog.deleteMany({where:{actorId:{in:[founderId,userId]}}});await db.seeraOrderLine.deleteMany({where:{order:{idempotencyKey:{in:operationIds}}}});await db.seeraSalesOrder.deleteMany({where:{idempotencyKey:{in:operationIds}}});if(sessionId)await db.seeraWorkSession.deleteMany({where:{id:sessionId}});if(skuId)await db.seeraPriceVersion.deleteMany({where:{skuId}});if(skuId)await db.seeraSku.deleteMany({where:{id:skuId}});if(retailerId)await db.seeraRetailer.deleteMany({where:{id:retailerId}});if(partnerId)await db.seeraPartyUser.deleteMany({where:{partnerId}});if(userId)await db.userRoleAssignment.deleteMany({where:{userId}});if(roleId&&permissionId)await db.rolePermission.deleteMany({where:{roleId,permissionId}});if(partnerId)await db.seeraPartner.deleteMany({where:{id:partnerId}});if(roleId)await db.role.deleteMany({where:{id:roleId}});if(ownsPermission&&permissionId)await db.permission.deleteMany({where:{id:permissionId}});if(userId)await db.user.deleteMany({where:{id:userId}});if(founderId)await db.user.deleteMany({where:{id:founderId}});console.log(JSON.stringify({correlationId,flow,event:"teardown",status:"PASS",durationMs:Date.now()-started,maxConcurrent}));}finally{const at=Date.now();await db.$disconnect();console.log(JSON.stringify({correlationId,flow,event:"disconnect",durationMs:Date.now()-at}));}},120_000);

describe(`Phase 11 isolated offline Flow ${flow}`,()=>{
 it.runIf(flow==="4")("fails closed for a retailer deactivated while offline",async()=>{await step("bootstrap-active-cache","offlineBootstrap",()=>offlineBootstrap(db,userId));await step("deactivate-retailer","SeeraRetailer.update",()=>db.seeraRetailer.update({where:{id:retailerId},data:{lifecycle:"DEACTIVATED"}}));await reconnect();await step("reconnect-auth","User.findUnique",()=>db.user.findUniqueOrThrow({where:{id:userId},select:{status:true}}));const input=operation();await expect(step("sync-denied","syncOfflineOperation",()=>syncOfflineOperation(db,userId,input))).rejects.toMatchObject({conflict:{classification:"SERVER_REJECTED",code:"RETAILER_DEACTIVATED"}});const stored=await step("verify-queue","SeeraOfflineOperation.findUniqueOrThrow",()=>db.seeraOfflineOperation.findUniqueOrThrow({where:{userId_clientOperationId:{userId,clientOperationId:input.clientOperationId}}}));expect(stored).toMatchObject({status:"CONFLICT",conflictClass:"SERVER_REJECTED",lastErrorCode:"RETAILER_DEACTIVATED"});expect(stored.originalPayload).toEqual(input.payload);expect(await step("verify-no-order","SeeraSalesOrder.count",()=>db.seeraSalesOrder.count({where:{idempotencyKey:input.clientOperationId}}))).toBe(0);});
 it.runIf(flow==="6")("replays uncertain delivery with exactly one business write",async()=>{await step("bootstrap-active-cache","offlineBootstrap",()=>offlineBootstrap(db,userId));await reconnect();await step("reconnect-auth","User.findUnique",()=>db.user.findUniqueOrThrow({where:{id:userId},select:{status:true}}));const input=operation();const first=await step("first-delivery","syncOfflineOperation",()=>syncOfflineOperation(db,userId,input));const replay1=await step("uncertain-response-replay-1","syncOfflineOperation",()=>syncOfflineOperation(db,userId,input));const replay2=await step("uncertain-response-replay-2","syncOfflineOperation",()=>syncOfflineOperation(db,userId,input));expect(replay1.id).toBe(first.id);expect(replay2.id).toBe(first.id);expect(await step("verify-one-order","SeeraSalesOrder.count",()=>db.seeraSalesOrder.count({where:{idempotencyKey:input.clientOperationId}}))).toBe(1);expect(await step("verify-one-operation","SeeraOfflineOperation.count",()=>db.seeraOfflineOperation.count({where:{userId,clientOperationId:input.clientOperationId,status:"SYNCED"}}))).toBe(1);expect(await step("verify-one-audit","AuditLog.count",()=>db.auditLog.count({where:{actorId:userId,action:"offline.operation.synced",entityId:first.id}}))).toBe(1);});
});
