import type {Prisma,PrismaClient} from "@prisma/client";import {FoundationError} from "@/lib/foundation/errors";import {recordAudit} from "@/lib/foundation/audit-service";import {offlineOperationSchema,type OfflineOperationInput} from "./offline-contract";import {classifyOfflineConflict} from "./conflict-engine";import {placeRetailerOrder,endFieldDay} from "@/lib/sales-distribution/workflow-service";import {recordCollection,captureMarketIntelligence} from "@/lib/sales-distribution/operational-service";
const p=<T>(value:unknown)=>value as T;
async function dispatch(db:PrismaClient,userId:string,input:OfflineOperationInput){const data=input.payload;
 if(input.actionType==="ORDER_DRAFT"){const retailer=await db.seeraRetailer.findUnique({where:{id:p<string>(data.retailerId)}}),lines=p<Array<{skuId:string;quantity:number;priceSnapshot?:number}>>(data.lines),skus=await db.seeraSku.findMany({where:{id:{in:lines.map(x=>x.skuId)}},include:{prices:{where:{tier:"DISTRIBUTOR_TO_RETAILER",status:"ACTIVE",effectiveFrom:{lte:new Date()},OR:[{effectiveTo:null},{effectiveTo:{gt:new Date()}}]},orderBy:{effectiveFrom:"desc"},take:1}}});const priceChanged=lines.some(line=>line.priceSnapshot!==undefined&&Number(skus.find(s=>s.id===line.skuId)?.prices[0]?.amount)!==line.priceSnapshot),conflict=classifyOfflineConflict({userActive:true,sessionActive:true,retailerActive:retailer?.lifecycle==="ACTIVE",skuActive:skus.length===lines.length&&skus.every(s=>s.status==="ACTIVE"),assignmentChanged:retailer?.distributorId!==p<string>(data.commercialPartyId),priceChanged});if(conflict)throw Object.assign(new FoundationError(conflict.code,"Offline order requires conflict resolution",409),{conflict});return placeRetailerOrder(db,{actorId:userId,sourcePortal:"sales-executive",commercialPartyType:"DISTRIBUTOR",commercialPartyId:p<string>(data.commercialPartyId)},{retailerId:p<string>(data.retailerId),idempotencyKey:input.clientOperationId,notes:p<string|undefined>(data.notes),lines});}
 if(input.actionType==="COLLECTION_DRAFT")return recordCollection(db,userId,{retailerId:p<string>(data.retailerId),amount:p<number>(data.amount),paymentMode:p<string>(data.paymentMode),reference:p<string|undefined>(data.reference),remarks:p<string|undefined>(data.remarks),idempotencyKey:input.clientOperationId});
 if(input.actionType==="MARKET_INTELLIGENCE_DRAFT")return captureMarketIntelligence(db,userId,p<Parameters<typeof captureMarketIntelligence>[2]>(data));
 if(input.actionType==="DAY_END_DRAFT"){await endFieldDay(db,userId,p<string>(data.sessionId),{outcome:p<string>(data.outcome),remarks:p<string|undefined>(data.remarks)});return{id:p<string>(data.sessionId)};}
 if(input.actionType==="VISIT_DRAFT"){const session=await db.seeraWorkSession.findFirst({where:{id:p<string>(data.workSessionId),employeeId:userId,status:"ACTIVE"}}),retailer=await db.seeraRetailer.findFirst({where:{id:p<string>(data.retailerId),salespersonId:userId,lifecycle:"ACTIVE"}});const conflict=classifyOfflineConflict({userActive:true,sessionActive:Boolean(session),retailerActive:Boolean(retailer),visitDuplicate:Boolean(await db.seeraVisit.findUnique({where:{idempotencyKey:input.clientOperationId}}))});if(conflict?.classification==="AUTO_RESOLVABLE")return await db.seeraVisit.findUniqueOrThrow({where:{idempotencyKey:input.clientOperationId}});if(conflict)throw Object.assign(new FoundationError(conflict.code,"Offline visit conflict",409),{conflict});return db.seeraVisit.create({data:{workSessionId:session!.id,retailerId:retailer!.id,checkedInAt:input.localCreatedAt,checkInLatitude:p<number|undefined>(data.latitude),checkInLongitude:p<number|undefined>(data.longitude),gpsExceptionReason:p<string|undefined>(data.gpsExceptionReason),idempotencyKey:input.clientOperationId}});}
 throw new FoundationError("OFFLINE_ACTION_REVIEW_REQUIRED","This offline draft requires user review before authoritative submission",409);
}
export async function syncOfflineOperation(db:PrismaClient,userId:string,raw:unknown){const input=offlineOperationSchema.parse(raw),user=await db.user.findUnique({where:{id:userId},select:{status:true}});if(user?.status!=="ACTIVE")throw new FoundationError("OFFLINE_IDENTITY_REVOKED","Offline sync identity is unavailable",403);const existing=await db.seeraOfflineOperation.findUnique({where:{userId_clientOperationId:{userId,clientOperationId:input.clientOperationId}}});if(existing?.status==="SYNCED")return existing;const operation=existing??await db.seeraOfflineOperation.create({data:{clientOperationId:input.clientOperationId,userId,deviceId:input.deviceId,sessionContext:input.sessionContext,entityType:input.entityType,actionType:input.actionType,localCreatedAt:input.localCreatedAt,payloadVersion:input.payloadVersion,originalPayload:input.payload as Prisma.InputJsonValue}});await db.seeraOfflineOperation.update({where:{id:operation.id},data:{status:"SYNCING",retryCount:{increment:existing?1:0}}});try{const result=await dispatch(db,userId,input);const acknowledgment={entityId:"id" in result?String(result.id):operation.id,actionType:input.actionType};const synced=await db.seeraOfflineOperation.update({where:{id:operation.id},data:{status:"SYNCED",serverAcknowledgment:acknowledgment,syncedAt:new Date(),lastErrorCode:null}});await recordAudit(db,{actorId:userId,action:"offline.operation.synced",entityType:"SeeraOfflineOperation",entityId:operation.id,details:acknowledgment});return synced;}catch(error){const conflict=typeof error==="object"&&error&&"conflict" in error?p<{classification:"AUTO_RESOLVABLE"|"USER_REVIEW_REQUIRED"|"SERVER_REJECTED";code:string}>((error as {conflict:unknown}).conflict):null;await db.seeraOfflineOperation.update({where:{id:operation.id},data:{status:conflict?"CONFLICT":"FAILED",conflictClass:conflict?.classification,conflictDetails:conflict as Prisma.InputJsonValue|undefined,lastErrorCode:conflict?.code??(typeof error==="object"&&error&&"code" in error?String(error.code):"SYNC_FAILED")}});throw error;}}
export async function listOfflineQueue(db:PrismaClient,userId:string){return db.seeraOfflineOperation.findMany({where:{userId},take:100,orderBy:{localCreatedAt:"desc"}});}
