"use client";
import {backoffMs,type OfflineQueueStatus} from "./offline-contract";
export type ClientQueuedOperation={clientOperationId:string;deviceId:string;sessionContext:{sessionId:string;appVersion:string;platform:string};entityType:string;actionType:string;localCreatedAt:string;payloadVersion:1;payload:Record<string,unknown>;status:OfflineQueueStatus;retryCount:number;lastError?:string;nextRetryAt?:number};
const DB="seera-field-offline-v1",STORE="operations",CACHE="bootstrap";
function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:"clientOperationId"});if(!db.objectStoreNames.contains(CACHE))db.createObjectStore(CACHE);};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function tx<T>(store:string,mode:IDBTransactionMode,run:(s:IDBObjectStore)=>IDBRequest<T>){const db=await openDb();return new Promise<T>((resolve,reject)=>{const request=run(db.transaction(store,mode).objectStore(store));request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
export async function queueOfflineOperation(input:Omit<ClientQueuedOperation,"status"|"retryCount">){const item={...input,status:"PENDING" as const,retryCount:0};await tx(STORE,"readwrite",s=>s.put(item));return item;}
export async function listClientQueue(){return tx<ClientQueuedOperation[]>(STORE,"readonly",s=>s.getAll());}
export async function cacheOfflineBootstrap(value:unknown){await tx(CACHE,"readwrite",s=>s.put({value,cachedAt:Date.now()},"current"));}
export async function readOfflineBootstrap(){return tx<{value:unknown;cachedAt:number}|undefined>(CACHE,"readonly",s=>s.get("current"));}
export async function syncClientQueue(fetcher:typeof fetch=fetch,now=Date.now()){const items=(await listClientQueue()).filter(x=>["PENDING","FAILED"].includes(x.status)&&(!x.nextRetryAt||x.nextRetryAt<=now));for(const item of items){await tx(STORE,"readwrite",s=>s.put({...item,status:"SYNCING"}));try{const response=await fetcher("/api/offline/sync",{method:"POST",headers:{"Content-Type":"application/json","X-Client-Operation-Id":item.clientOperationId},body:JSON.stringify(item)}),body=await response.json();if(response.ok)await tx(STORE,"readwrite",s=>s.put({...item,status:"SYNCED",serverAcknowledgment:body.operation}));else{const conflict=response.status===409;await tx(STORE,"readwrite",s=>s.put({...item,status:conflict?"CONFLICT":"FAILED",retryCount:item.retryCount+1,lastError:body?.error?.code??"SYNC_FAILED",nextRetryAt:conflict?undefined:now+backoffMs(item.retryCount)}));}}catch(error){await tx(STORE,"readwrite",s=>s.put({...item,status:"FAILED",retryCount:item.retryCount+1,lastError:error instanceof Error?error.message:"NETWORK_ERROR",nextRetryAt:now+backoffMs(item.retryCount)}));}}return listClientQueue();}
