import { createHash } from "node:crypto";
import type { FinancialEntryType, Prisma, PrismaClient } from "@prisma/client";
import { authorize } from "@/lib/foundation/authorization-service";
import { recordAudit } from "@/lib/foundation/audit-service";
import { FoundationError } from "@/lib/foundation/errors";
import { ageingBucket } from "./phase6-9-rules";

const numberFor = (prefix: string, key: string) => `${prefix}-${createHash("sha256").update(key).digest("hex").slice(0, 16).toUpperCase()}`;

export async function recordPayment(db: PrismaClient, actorId: string, input: { payerType: string; payerId: string; payeeType: string; payeeId: string; amountClaimed: number; reference: string; paymentMode: string; paymentDate: Date; proofId?: string; idempotencyKey: string }) { await authorize(db, { actorId, permission: "payment:review" }); if (input.amountClaimed <= 0) throw new FoundationError("INVALID_PAYMENT_AMOUNT", "Payment amount must be positive", 400); return db.$transaction(async tx=>{const duplicateReference=await tx.seeraPaymentRecord.findFirst({where:{reference:input.reference,payerId:input.payerId,payeeId:input.payeeId,paymentDate:input.paymentDate}});if(duplicateReference)throw new FoundationError("DUPLICATE_PAYMENT_REFERENCE","Duplicate UTR/payment reference",409);const payment=await tx.seeraPaymentRecord.create({data:{...input,paymentNumber:numberFor("PAY",input.idempotencyKey),unappliedAmount:0}});await recordAudit(tx,{actorId,action:"payment.recorded",entityType:"SeeraPaymentRecord",entityId:payment.id,afterState:{reference:input.reference,amount:input.amountClaimed}});return payment;}); }

export async function postLedgerEntry(db: PrismaClient, actorId: string, input: { type: FinancialEntryType; debitPartyType: string; debitPartyId: string; creditPartyType: string; creditPartyId: string; amount: number; documentId?: string; orderId?: string; claimId?: string; taClaimId?: string; reason: string; commercialSnapshot: Prisma.InputJsonValue; idempotencyKey: string; approverId?: string }) {
  await authorize(db, { actorId, permission: "ledger:post" }); if (input.amount <= 0) throw new FoundationError("INVALID_LEDGER_AMOUNT", "Ledger amount must be positive", 400);
  return db.$transaction(async (tx) => { const existing = await tx.seeraFinancialEntry.findUnique({ where: { idempotencyKey: input.idempotencyKey } }); if (existing) return existing; const entry = await tx.seeraFinancialEntry.create({ data: { ...input, actorId, entryNumber: numberFor("LE", input.idempotencyKey), status: "POSTED", postedAt: new Date() } }); await recordAudit(tx, { actorId, action: "ledger.posted", entityType: "SeeraFinancialEntry", entityId: entry.id, afterState: { type: entry.type, amount: entry.amount.toString(), debitPartyId: entry.debitPartyId, creditPartyId: entry.creditPartyId } }); return entry; });
}

export async function reverseLedgerEntry(db: PrismaClient, actorId: string, originalEntryId: string, input: { reason: string; idempotencyKey: string; approverId: string }) {
  await authorize(db, { actorId, permission: "ledger:reverse" });
  return db.$transaction(async (tx) => { const original = await tx.seeraFinancialEntry.findUniqueOrThrow({ where: { id: originalEntryId } }); if (original.status !== "POSTED") throw new FoundationError("ENTRY_NOT_REVERSIBLE", "Only posted entries may be reversed", 409); const existing = await tx.seeraFinancialEntry.findUnique({ where: { idempotencyKey: input.idempotencyKey } }); if (existing) return existing; const reversal = await tx.seeraFinancialEntry.create({ data: { entryNumber: numberFor("RV", input.idempotencyKey), type: "REVERSAL", status: "POSTED", debitPartyType: original.creditPartyType, debitPartyId: original.creditPartyId, creditPartyType: original.debitPartyType, creditPartyId: original.debitPartyId, amount: original.amount, currency: original.currency, documentId: original.documentId, orderId: original.orderId, claimId: original.claimId, taClaimId: original.taClaimId, originalEntryId: original.id, commercialSnapshot: original.commercialSnapshot as Prisma.InputJsonValue, actorId, approverId: input.approverId, reason: input.reason, idempotencyKey: input.idempotencyKey, postedAt: new Date() } }); await tx.seeraFinancialEntry.update({ where: { id: original.id }, data: { status: "REVERSED", reversedAt: new Date() } }); await recordAudit(tx, { actorId, action: "ledger.reversed", entityType: "SeeraFinancialEntry", entityId: original.id, afterState: { reversalId: reversal.id, reason: input.reason } }); return reversal; });
}

export async function verifyPayment(db: PrismaClient, actorId: string, paymentId: string, input: { matchedAmount: number; reason: string }) {
  await authorize(db, { actorId, permission: "payment:review" }); await authorize(db,{actorId,permission:"ledger:post"});
  return db.$transaction(async (tx) => { const payment = await tx.seeraPaymentRecord.findUniqueOrThrow({ where: { id: paymentId } }); if (input.matchedAmount < 0 || input.matchedAmount > Number(payment.amountClaimed)) throw new FoundationError("INVALID_MATCHED_AMOUNT", "Matched amount exceeds claimed payment", 400); const status = input.matchedAmount === Number(payment.amountClaimed) ? "VERIFIED" : input.matchedAmount > 0 ? "PARTIALLY_MATCHED" : "REJECTED"; const result = await tx.seeraPaymentRecord.update({ where: { id: payment.id }, data: { amountMatched: input.matchedAmount, unappliedAmount: input.matchedAmount, status, reviewerId: actorId, reviewReason: input.reason, reviewedAt: new Date() } }); if(input.matchedAmount>0)await tx.seeraFinancialEntry.upsert({where:{idempotencyKey:`${payment.idempotencyKey}:verified-ledger`},update:{},create:{entryNumber:numberFor("ADV",payment.idempotencyKey),type:"ADVANCE",status:"POSTED",debitPartyType:payment.payeeType,debitPartyId:payment.payeeId,creditPartyType:payment.payerType,creditPartyId:payment.payerId,amount:input.matchedAmount,commercialSnapshot:{paymentNumber:payment.paymentNumber,reference:payment.reference},actorId,reason:input.reason,idempotencyKey:`${payment.idempotencyKey}:verified-ledger`,postedAt:new Date()}}); await recordAudit(tx, { actorId, action: "payment.verified", entityType: "SeeraPaymentRecord", entityId: payment.id, afterState: { matchedAmount: input.matchedAmount, status } }); return result; });
}

export async function allocateVerifiedPayment(db: PrismaClient, actorId: string, paymentId: string, allocations: { documentId: string; amount: number; idempotencyKey: string; reason: string }[]) {
  await authorize(db, { actorId, permission: "payment:allocate" });
  return db.$transaction(async (tx) => { const payment = await tx.seeraPaymentRecord.findUniqueOrThrow({ where: { id: paymentId }, include: { allocations: { where: { status: "ACTIVE" } } } }); if (!(["VERIFIED", "PARTIALLY_MATCHED", "ADVANCE_HELD"] as string[]).includes(payment.status)) throw new FoundationError("PAYMENT_NOT_VERIFIED", "Payment must be verified before allocation", 409); const requested = allocations.reduce((sum, item) => sum + item.amount, 0); if (allocations.some((item) => item.amount <= 0) || requested > Number(payment.unappliedAmount)) throw new FoundationError("PAYMENT_OVER_ALLOCATION", "Allocation exceeds unapplied payment", 409); const duplicate = await tx.seeraPaymentAllocation.findFirst({ where: { idempotencyKey: { in: allocations.map((item) => item.idempotencyKey) } } }); if (duplicate) throw new FoundationError("DUPLICATE_ALLOCATION", "Allocation already exists", 409); const documents = await tx.seeraCommercialDocument.findMany({ where: { id: { in: allocations.map((item) => item.documentId) }, buyerId: payment.payerId, issuerId: payment.payeeId, status: "ISSUED" }, select: { id: true } }); if (documents.length !== new Set(allocations.map((item) => item.documentId)).size) throw new FoundationError("ALLOCATION_SCOPE_DENIED", "Invoice scope mismatch", 403); const created = []; for (const item of allocations) created.push(await tx.seeraPaymentAllocation.create({ data: { paymentId, ...item, actorId } })); await tx.seeraPaymentRecord.update({ where: { id: paymentId }, data: { unappliedAmount: { decrement: requested } } }); await recordAudit(tx, { actorId, action: "payment.allocated", entityType: "SeeraPaymentRecord", entityId: paymentId, afterState: { requested, documents: allocations.map((item) => item.documentId) } }); return created; });
}

export async function ledgerReadModel(db: PrismaClient, actorId: string, input: { partyType: string; partyId: string; asOf?: Date }) {
  await authorize(db, { actorId, permission: "ledger:view" }); const asOf = input.asOf ?? new Date();
  const entries = await db.seeraFinancialEntry.findMany({ where: { status: "POSTED", OR: [{ debitPartyType: input.partyType, debitPartyId: input.partyId }, { creditPartyType: input.partyType, creditPartyId: input.partyId }] }, orderBy: [{ postedAt: "asc" }, { createdAt: "asc" }] });
  const debit = entries.filter((e) => e.debitPartyId === input.partyId && e.debitPartyType === input.partyType).reduce((s, e) => s + Number(e.amount), 0); const credit = entries.filter((e) => e.creditPartyId === input.partyId && e.creditPartyType === input.partyType).reduce((s, e) => s + Number(e.amount), 0);
  const documents = await db.seeraCommercialDocument.findMany({ where: { buyerType: input.partyType, buyerId: input.partyId, status: "ISSUED", type: { in: ["TAX_INVOICE", "NON_TAX_INVOICE", "DEBIT_NOTE"] } } }); const documentIds=documents.map(d=>d.id); const orderIds=documents.flatMap(d=>d.orderId?[d.orderId]:[]);
  const [allocations,notes,orders,promises,extensions,unapplied]=await Promise.all([db.seeraPaymentAllocation.findMany({where:{documentId:{in:documentIds},status:"ACTIVE"}}),db.seeraCommercialDocument.findMany({where:{originalDocumentId:{in:documentIds},status:"ISSUED",type:{in:["CREDIT_NOTE","DEBIT_NOTE"]}}}),db.seeraSalesOrder.findMany({where:{id:{in:orderIds}}}),db.seeraPaymentPromise.findMany({where:{orderId:{in:orderIds}},orderBy:{createdAt:"desc"}}),db.seeraCreditExtension.findMany({where:{orderId:{in:orderIds},status:"APPROVED"},orderBy:{approvedAt:"desc"}}),db.seeraPaymentRecord.aggregate({where:{payerType:input.partyType,payerId:input.partyId},_sum:{unappliedAmount:true}})]);
  const allocated=new Map<string,number>();allocations.forEach(a=>allocated.set(a.documentId,(allocated.get(a.documentId)??0)+Number(a.amount)));const noteEffect=new Map<string,number>();notes.forEach(note=>{if(note.originalDocumentId)noteEffect.set(note.originalDocumentId,(noteEffect.get(note.originalDocumentId)??0)+(note.type==="CREDIT_NOTE"?-Number(note.grandTotal):Number(note.grandTotal)));});
  const outstanding=documents.map(document=>{const order=orders.find(o=>o.id===document.orderId);const terms=document.paymentTermsSnapshot as {originalDueDate?:string}|null;const originalDueDate=order?.originalDueDate??(terms?.originalDueDate?new Date(terms.originalDueDate):document.issueDate??document.createdAt);const promise=promises.find(p=>p.orderId===document.orderId);const extension=extensions.find(e=>e.orderId===document.orderId);const amount=Math.max(0,Number(document.grandTotal)+(noteEffect.get(document.id)??0)-(allocated.get(document.id)??0));return{documentId:document.id,documentNumber:document.documentNumber,originalDueDate,graceUntil:order?.graceUntil??null,promisedPaymentDate:promise?.promisedPaymentDate??null,formalExtensionUntil:extension?.extensionUntil??null,actualOverdue:asOf>originalDueDate,amount,ageingBucket:ageingBucket(originalDueDate,asOf)};}).filter(item=>item.amount>0);
  return { balance: debit-credit, debit, credit, outstandingTotal: outstanding.reduce((s,i)=>s+i.amount,0), outstanding, advancesAndUnapplied:Number(unapplied._sum.unappliedAmount??0), allocations, transactions:entries };
}

export async function reconcilePayment(db: PrismaClient, actorId: string, input: { paymentId: string; idempotencyKey: string }) { await authorize(db, { actorId, permission: "reconciliation:manage" }); return db.$transaction(async (tx) => { const payment = await tx.seeraPaymentRecord.findUniqueOrThrow({ where: { id: input.paymentId }, include: { allocations: { where: { status: "ACTIVE" } } } }); const allocated = payment.allocations.reduce((s, a) => s + Number(a.amount), 0); const matched = Number(payment.amountMatched); const difference = matched - allocated - Number(payment.unappliedAmount); const status = difference === 0 ? (allocated === matched ? "MATCHED" : "PARTIALLY_MATCHED") : "EXCEPTION"; const result = await tx.seeraFinancialReconciliation.upsert({ where: { idempotencyKey: input.idempotencyKey }, update: {}, create: { referenceType: "PAYMENT", referenceId: payment.id, expectedAmount: matched, matchedAmount: allocated, difference, exceptionReason: difference === 0 ? undefined : "PAYMENT_LEDGER_DIFFERENCE", actorId, status, idempotencyKey: input.idempotencyKey } }); await recordAudit(tx, { actorId, action: "finance.reconciled", entityType: "SeeraFinancialReconciliation", entityId: result.id, afterState: { status, difference } }); return result; }); }

export async function settleClaim(db: PrismaClient, actorId: string, input: { claimId: string; outcome: "CREDIT_NOTE" | "DEBIT_NOTE" | "REPLACEMENT" | "NO_FINANCIAL_EFFECT"; approvedAmount: number; rejectedAmount: number; reason: string; approverId: string; documentId?: string; financialEntryId?: string }) { await authorize(db, { actorId, permission: "claim_settlement:manage" }); if (input.approvedAmount < 0 || input.rejectedAmount < 0) throw new FoundationError("INVALID_CLAIM_SETTLEMENT", "Invalid claim settlement", 400); return db.$transaction(async (tx) => { const settlement = await tx.seeraClaimSettlement.create({ data: { ...input, actorId, status: "APPROVED" } }); await recordAudit(tx, { actorId, action: "claim.settled", entityType: "SeeraClaimSettlement", entityId: settlement.id, afterState: { outcome: input.outcome, approvedAmount: input.approvedAmount } }); return settlement; }); }
