export type Insight={code:string;severity:"INFO"|"SUCCESS"|"WARNING"|"HIGH"|"CRITICAL";explanation:string;sourceMetrics:Record<string,unknown>;generatedAt:string;confidence?:number;actionPath?:string;expiresAt?:string};
const result=(code:Insight['code'],severity:Insight['severity'],explanation:string,sourceMetrics:Record<string,unknown>,now:Date,actionPath?:string):Insight=>({code,severity,explanation,sourceMetrics,generatedAt:now.toISOString(),confidence:1,actionPath,expiresAt:new Date(now.getTime()+7*86400000).toISOString()});
export function nextRetailer(input:{name:string;lastOrderDays:number;typicalCycleDays:number;followUpDue:boolean;outstanding:number;actionPath?:string},now=new Date()){const overdue=input.lastOrderDays-input.typicalCycleDays;if(overdue<0&&!input.followUpDue)return null;return result("NEXT_RETAILER",input.outstanding>0?"HIGH":"WARNING",`Visit ${input.name} — last order ${input.lastOrderDays} days ago; typical reorder cycle ${input.typicalCycleDays} days${input.followUpDue?"; follow-up is due":""}.`,{lastOrderDays:input.lastOrderDays,typicalCycleDays:input.typicalCycleDays,followUpDue:input.followUpDue,outstanding:input.outstanding},now,input.actionPath);}
export function dormantRetailer(name:string,lastDeliveredDays:number,thresholdDays:number,now=new Date()){return lastDeliveredDays>=thresholdDays?result("DORMANT_RETAILER","WARNING",`${name} has no delivered order for ${lastDeliveredDays} days; dormant threshold is ${thresholdDays} days.`,{lastDeliveredDays,thresholdDays},now):null;}
export function reorderSignal(stock:number,recentDailyDemand:number,leadTimeDays:number,now=new Date()){const coverage=recentDailyDemand>0?stock/recentDailyDemand:Infinity;return coverage<=leadTimeDays?result("REORDER_SIGNAL","HIGH",`Stock coverage is ${Number.isFinite(coverage)?coverage.toFixed(1):"unlimited"} days against ${leadTimeDays} days lead time. Review replenishment; no order was created.`,{stock,recentDailyDemand,leadTimeDays,coverage},now):null;}
export function stockRisk(stock:number,openDemand:number,leadTimeDemand:number,now=new Date()){const gap=openDemand+leadTimeDemand-stock;return gap>0?result("STOCK_SHORTAGE_RISK",gap>stock?"CRITICAL":"HIGH",`Projected demand exceeds current stock by ${gap}.`,{stock,openDemand,leadTimeDemand,gap},now):null;}
export function targetGap(target:number,achieved:number,daysRemaining:number,recentDailyRunRate:number,now=new Date()){const gap=Math.max(0,target-achieved),required=daysRemaining?gap/daysRemaining:gap;return gap>0?result("TARGET_GAP",recentDailyRunRate<required?"HIGH":"WARNING",`Target gap is ${gap}; required daily run rate is ${required.toFixed(2)} versus recent ${recentDailyRunRate.toFixed(2)}.`,{target,achieved,gap,daysRemaining,requiredDailyRunRate:required,recentDailyRunRate},now):null;}
export function collectionPriority(overdueAmount:number,overdueDays:number,promiseMissed:boolean,creditUtilization:number,now=new Date()){const score=overdueAmount*Math.max(1,overdueDays)*(promiseMissed?2:1)*(1+creditUtilization);return result("COLLECTION_PRIORITY",promiseMissed||overdueDays>30?"CRITICAL":"HIGH",`Prioritize collection: ₹${overdueAmount.toFixed(2)} overdue by ${overdueDays} days${promiseMissed?"; promised payment date missed":""}.`,{overdueAmount,overdueDays,promiseMissed,creditUtilization,score},now);}
export function slowMovingSku(input:{skuCode:string;movementQuantity:number;windowDays:number;maximumMovement:number;actionPath?:string},now=new Date()){if(input.movementQuantity>input.maximumMovement)return null;return result("SLOW_MOVING_SKU","WARNING",`SKU ${input.skuCode} moved ${input.movementQuantity} units in ${input.windowDays} days; configured maximum for a slow-moving signal is ${input.maximumMovement}.`,{skuCode:input.skuCode,movementQuantity:input.movementQuantity,windowDays:input.windowDays,maximumMovement:input.maximumMovement},now,input.actionPath);}
export function distributorDevelopment(input:{prospectName:string;daysSinceActivity:number;staleDays:number;followUpDue:boolean;status:string;actionPath?:string},now=new Date()){if(input.status==="APPROVED"||input.status==="ACTIVE"||(!input.followUpDue&&input.daysSinceActivity<input.staleDays))return null;return result("DISTRIBUTOR_DEVELOPMENT","WARNING",`Follow up with ${input.prospectName}: ${input.daysSinceActivity} days since pipeline activity${input.followUpDue?" and follow-up is due":""}. Review the prospect; activation remains an approved manual action.`,{daysSinceActivity:input.daysSinceActivity,staleDays:input.staleDays,followUpDue:input.followUpDue,status:input.status,automaticActivation:false},now,input.actionPath);}
export function fulfilmentRisk(input:{orderNumber:string;pendingHours:number;maximumPendingHours:number;partialPending:boolean;stockInsufficient:boolean;creditHold:boolean;operationalException?:string;actionPath?:string},now=new Date()){const reasons:string[]=[];if(input.pendingHours>input.maximumPendingHours)reasons.push(`pending ${input.pendingHours} hours`);if(input.partialPending)reasons.push("partial quantity remains pending");if(input.stockInsufficient)reasons.push("insufficient stock");if(input.creditHold)reasons.push("credit hold");if(input.operationalException)reasons.push(input.operationalException);if(!reasons.length)return null;return result("FULFILMENT_RISK",input.creditHold||input.stockInsufficient?"HIGH":"WARNING",`Order ${input.orderNumber} needs attention: ${reasons.join("; ")}.`,{pendingHours:input.pendingHours,maximumPendingHours:input.maximumPendingHours,partialPending:input.partialPending,stockInsufficient:input.stockInsufficient,creditHold:input.creditHold,operationalException:input.operationalException??null},now,input.actionPath);}
