export const REPORT_CATALOG={
  DAILY_SALES:"SALES",MONTHLY_SALES:"SALES",MONTH_BY_MONTH_SALES:"SALES",BOOKED_VS_DELIVERED:"SALES",TARGET_VS_ACHIEVEMENT:"SALES",TERRITORY_SALES:"SALES",SALESPERSON_SALES:"SALES",MANAGER_TEAM_SALES:"SALES",DISTRIBUTOR_SALES:"SALES",SUPER_STOCKIST_SALES:"SALES",SKU_SALES:"SALES",PRODUCT_SALES:"SALES",
  DAILY_WORKING:"FIELD",ATTENDANCE:"FIELD",VISIT_REPORT:"FIELD",PRODUCTIVE_VISITS:"FIELD",BEAT_COVERAGE:"FIELD",RETAILER_COVERAGE:"FIELD",JOINT_WORKING:"FIELD",MANAGER_RETAILING:"FIELD",DISTRIBUTOR_DEVELOPMENT:"FIELD",MARKET_INTELLIGENCE:"FIELD",
  LEDGER:"FINANCE",OUTSTANDING:"FINANCE",AGEING:"FINANCE",COLLECTION:"FINANCE",PAYMENT_ALLOCATION:"FINANCE",ADVANCE:"FINANCE",CREDIT_NOTE:"FINANCE",DEBIT_NOTE:"FINANCE",CLAIMS_SETTLEMENT:"FINANCE",RECONCILIATION:"FINANCE",TA:"FINANCE",
  STOCK_SUMMARY:"INVENTORY",STOCK_MOVEMENT:"INVENTORY",OPENING_CLOSING:"INVENTORY",STOCK_RECONCILIATION:"INVENTORY",SLOW_MOVING:"INVENTORY",NON_MOVING:"INVENTORY",LOW_STOCK:"INVENTORY",SKU_MOVEMENT:"INVENTORY",
  DISTRIBUTOR_MASTER:"PARTNER",SUPER_STOCKIST_MASTER:"PARTNER",PROSPECT_PIPELINE:"PARTNER",PARTNER_LIFECYCLE:"PARTNER",PARTNER_STATUS:"PARTNER",
  INVOICE_REGISTER:"DOCUMENTS",CREDIT_NOTE_REGISTER:"DOCUMENTS",DEBIT_NOTE_REGISTER:"DOCUMENTS",CHALLAN_REGISTER:"DOCUMENTS",MANUAL_DOCUMENT_REGISTER:"DOCUMENTS"
} as const;
const formulaDanger=/^[=+\-@\t\r]/;
export function csvCell(value:unknown){let text=value==null?"":String(value);if(formulaDanger.test(text))text=`'${text}`;return `"${text.replace(/"/g,'""')}"`;}
export function toCsv(rows:Record<string,unknown>[],allowedColumns:string[]){return[allowedColumns.map(csvCell).join(","),...rows.map(row=>allowedColumns.map(k=>csvCell(row[k])).join(","))].join("\r\n");}
export function assertReportScope(requestedPartyId:string|undefined,allowedPartyIds:string[]|null){if(requestedPartyId&&allowedPartyIds&&!allowedPartyIds.includes(requestedPartyId))throw Object.assign(new Error("Report scope denied"),{code:"REPORT_SCOPE_DENIED",status:403});}
export function printableReport(title:string,headers:string[],rows:Record<string,unknown>[]){const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));return `<!doctype html><html><meta charset="utf-8"><title>${esc(title)}</title><style>body{font-family:system-ui;padding:24px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ddd;padding:8px;text-align:left}</style><h1>${esc(title)}</h1><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${headers.map(h=>`<td>${esc(r[h])}</td>`).join("")}</tr>`).join("")}</tbody></table></html>`;}
export async function pdfReport(title:string,headers:string[],rows:Record<string,unknown>[]){const{PDFDocument,StandardFonts,rgb}=await import("pdf-lib");const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica);let page=pdf.addPage([842,595]),y=555;const line=(text:string,size=9,color=rgb(0.1,0.1,0.1))=>{if(y<35){page=pdf.addPage([842,595]);y=555;}page.drawText(text.slice(0,145),{x:30,y,size,font,color});y-=size+7;};line(title,16,rgb(.6,.05,.05));line(headers.join(" | "),10,rgb(.1,.25,.6));for(const row of rows)line(headers.map(h=>String(row[h]??"")).join(" | "));return pdf.save();}
