import { getAiPrincipal } from "@/lib/muv-ai/authorization";
import { requireAiPermission } from "@/lib/muv-ai/security";
import { prisma } from "@/lib/prisma";

export default async function AiOperationsPage(){
 const p=await getAiPrincipal();requireAiPermission(p,"ai.operations.view");const since=new Date(Date.now()-24*3600000);
 const [providers,workflows,invocations,security,incidents,telemetry]=await Promise.all([prisma.aiProvider.findMany({orderBy:{priority:"asc"}}),prisma.aiWorkflow.groupBy({by:["status"],where:{organizationKey:p.organizationKey,createdAt:{gte:since}},_count:true}),prisma.aiModelInvocation.groupBy({by:["status"],where:{organizationKey:p.organizationKey,startedAt:{gte:since}},_count:true}),prisma.aiSecurityEvent.findMany({where:{organizationKey:p.organizationKey},orderBy:{createdAt:"desc"},take:20}),prisma.aiIncident.findMany({where:{organizationKey:p.organizationKey,status:{not:"CLOSED"}},orderBy:{detectedAt:"desc"},take:20}),prisma.aiTelemetry.aggregate({where:{organizationKey:p.organizationKey,createdAt:{gte:since}},_sum:{value:true},_count:true})]);
 return <section className="space-y-6 text-white"><header><h1 className="text-3xl font-semibold">AI Operational Health</h1><p className="text-sm text-zinc-400">Provider, workflow, validation, security, usage and incident governance.</p></header><div className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-white/10 p-5"><p>Providers</p><p className="mt-2 text-3xl">{providers.length}</p></article><article className="rounded-2xl border border-white/10 p-5"><p>Telemetry events (24h)</p><p className="mt-2 text-3xl">{telemetry._count}</p></article><article className="rounded-2xl border border-white/10 p-5"><p>Open incidents</p><p className="mt-2 text-3xl">{incidents.length}</p></article></div><div className="grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-white/10 p-5"><h2>Provider registry</h2>{providers.map(x=><p key={x.id} className="mt-3 text-sm">{x.name} · {x.status} · priority {x.priority}</p>)}<h2 className="mt-6">Workflow health</h2>{workflows.map(x=><p key={x.status} className="mt-2 text-sm">{x.status}: {x._count}</p>)}</article><article className="rounded-2xl border border-white/10 p-5"><h2>Security events</h2>{security.map(x=><p key={x.id} className="mt-3 text-sm">{x.severity} · {x.eventType} · {x.createdAt.toLocaleString()}</p>)}{!security.length?<p className="mt-3 text-sm text-zinc-500">No security events.</p>:null}<h2 className="mt-6">Invocation status</h2>{invocations.map(x=><p key={x.status} className="mt-2 text-sm">{x.status}: {x._count}</p>)}</article></div></section>;
}
