"use client";
import { useState, type FormEvent } from "react";

type Props = { portal: string; language: "EN" | "HI" };
const labels = { EN: { title:"Operational Workflows", document:"Document ID", download:"Download / Print", share:"Create Secure Link", recipient:"Recipient ID", manager:"Manager Retailing", session:"Work Session ID", retailer:"Retailer ID", checkin:"Retailer Check-in", prospect:"Distributor Prospect", business:"Business name", mobile:"Mobile", create:"Create Prospect", team:"Load Team Controls", finance:"Financial Control", party:"Party ID", ledger:"Load Ledger & Ageing", payment:"Payment ID", verify:"Verify Payment", ta:"TA / Partner Lifecycle", claim:"TA Claim ID", approve:"Approve & Pay", partner:"Partner ID", reactivate:"Reactivate Partner", result:"Result" }, HI: { title:"संचालन कार्यप्रवाह", document:"दस्तावेज़ आईडी", download:"डाउनलोड / प्रिंट", share:"सुरक्षित लिंक बनाएँ", recipient:"प्राप्तकर्ता आईडी", manager:"प्रबंधक रिटेलिंग", session:"कार्य सत्र आईडी", retailer:"खुदरा विक्रेता आईडी", checkin:"खुदरा चेक-इन", prospect:"वितरक संभावना", business:"व्यवसाय नाम", mobile:"मोबाइल", create:"संभावना बनाएँ", team:"टीम नियंत्रण देखें", finance:"वित्तीय नियंत्रण", party:"भागीदार आईडी", ledger:"खाता-बही और आयु देखें", payment:"भुगतान आईडी", verify:"भुगतान सत्यापित करें", ta:"यात्रा भत्ता / भागीदार जीवनचक्र", claim:"यात्रा दावा आईडी", approve:"स्वीकृत और भुगतान", partner:"भागीदार आईडी", reactivate:"भागीदार पुनः सक्रिय करें", result:"परिणाम" } } as const;
export function PhaseCompletionPanel({portal,language}:Props){const t=labels[language];const[result,setResult]=useState("");const call=async(url:string,init?:RequestInit)=>{const response=await fetch(url,init);const data=await response.json().catch(()=>({error:"Invalid response"}));setResult(JSON.stringify(data,null,2));if(!response.ok)throw new Error(data?.error?.message??"Request failed");return data;};const form=(event:FormEvent<HTMLFormElement>)=>Object.fromEntries(new FormData(event.currentTarget));
return <section style={{marginTop:32,padding:20,border:"1px solid #d7dbe4",borderRadius:12}}><h2>{t.title}</h2>
<form onSubmit={async e=>{e.preventDefault();const v=form(e);location.href=`/api/documents/${encodeURIComponent(String(v.documentId))}/download`;}}><label>{t.document}<input name="documentId" required style={{margin:8}}/></label><button>{t.download}</button></form>
<form onSubmit={async e=>{e.preventDefault();const v=form(e);await call(`/api/documents/${encodeURIComponent(String(v.documentId))}/share`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recipientType:"PARTNER",recipientId:v.recipientId,expiresAt:new Date(Date.now()+86400000).toISOString()})});}}><label>{t.document}<input name="documentId" required style={{margin:8}}/></label><label>{t.recipient}<input name="recipientId" required style={{margin:8}}/></label><button>{t.share}</button></form>
{portal==="sales-manager"&&<><h3>{t.manager}</h3><form onSubmit={async e=>{e.preventDefault();const v=form(e);await call("/api/manager/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"retailer-check-in",payload:{workSessionId:v.sessionId,retailerId:v.retailerId,idempotencyKey:crypto.randomUUID()}})});}}><input name="sessionId" placeholder={t.session} required/><input name="retailerId" placeholder={t.retailer} required/><button>{t.checkin}</button></form><h3>{t.prospect}</h3><form onSubmit={async e=>{e.preventDefault();const v=form(e);await call("/api/manager/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create-distributor-prospect",payload:{businessName:v.businessName,mobile:v.mobile,profile:{source:"MANAGER_PORTAL"}}})});}}><input name="businessName" placeholder={t.business} required/><input name="mobile" placeholder={t.mobile} required/><button>{t.create}</button></form><button onClick={()=>call("/api/manager/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"team-dashboard",payload:{}})})}>{t.team}</button></>}
{portal==="accounts"&&<><h3>{t.finance}</h3><form onSubmit={async e=>{e.preventDefault();const v=form(e);await call(`/api/finance/ledger?partyType=PARTNER&partyId=${encodeURIComponent(String(v.partyId))}`);}}><input name="partyId" placeholder={t.party} required/><button>{t.ledger}</button></form><form onSubmit={async e=>{e.preventDefault();const v=form(e);await call("/api/finance/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"verify-payment",payload:{paymentId:v.paymentId,matchedAmount:Number(v.amount),reason:"Verified from Accounts portal"}})});}}><input name="paymentId" placeholder={t.payment} required/><input name="amount" type="number" min="0" step="0.01" required/><button>{t.verify}</button></form></>}
{["accounts","founder-admin"].includes(portal)&&<><h3>{t.ta}</h3><form onSubmit={async e=>{e.preventDefault();const v=form(e);await call(`/api/partners/${encodeURIComponent(String(v.partnerId))}/lifecycle`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"REACTIVATE",reason:"Approved reactivation from governed portal",approverId:v.approverId,idempotencyKey:crypto.randomUUID()})});}}><input name="partnerId" placeholder={t.partner} required/><input name="approverId" placeholder="Approver ID" required/><button>{t.reactivate}</button></form></>}
{result&&<><h3>{t.result}</h3><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{result}</pre></>}</section>}
