"use client";
import{useRouter}from"next/navigation";import{useState}from"react";import styles from"./Workspace.module.css";
function Message({value}:{value:{type:"success"|"error";text:string}|null}){return value?<p role={value.type==="error"?"alert":"status"} className={`${styles.notice} ${value.type==="success"?styles.success:styles.danger}`}>{value.text}</p>:null}
async function request(url:string,init:RequestInit){const response=await fetch(url,init),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message??"Request failed");return data}
export function CreateUserForm({portal,roles,language}:{portal:string;roles:{code:string;name:string}[];language:"EN"|"HI"}){const router=useRouter(),[busy,setBusy]=useState(false),[message,setMessage]=useState<{type:"success"|"error";text:string}|null>(null),hi=language==="HI";return <form className={styles.form} onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage(null);try{const values=Object.fromEntries(new FormData(e.currentTarget)),created=await request("/api/foundation/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:values.email,name:values.name,password:values.password})});await request(`/api/foundation/users/${created.user.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"assign_role",roleCode:values.roleCode,reason:"Assigned during governed user creation"})});setMessage({type:"success",text:hi?"उपयोगकर्ता सफलतापूर्वक बनाया गया।":"User created successfully."});setTimeout(()=>router.push(`/portal/${portal}/users/${created.user.id}`),500)}catch(error){setMessage({type:"error",text:error instanceof Error?error.message:"Request failed"})}finally{setBusy(false)}}}><Message value={message}/><label>{hi?"पूरा नाम":"Full name"}<input name="name" required minLength={2}/></label><label>{hi?"ईमेल":"Email"}<input name="email" type="email" required/></label><label>{hi?"अस्थायी पासवर्ड":"Temporary password"}<input name="password" type="password" minLength={12} required/></label><label>{hi?"भूमिका":"Role"}<select name="roleCode" required>{roles.map(r=><option key={r.code} value={r.code}>{r.name}</option>)}</select></label><div className={styles.formActions}><button className={styles.button} disabled={busy}>{busy?(hi?"बनाया जा रहा है…":"Creating…"):(hi?"उपयोगकर्ता बनाएँ":"Create user")}</button></div></form>}
export function UserGovernanceForm({userId,user,roles,assignedRoleCodes,canManage,language}:{userId:string;user:{name:string;email:string;status:string};roles:{code:string;name:string}[];assignedRoleCodes:string[];canManage:boolean;language:"EN"|"HI"}){const router=useRouter(),[busy,setBusy]=useState(false),[message,setMessage]=useState<{type:"success"|"error";text:string}|null>(null),hi=language==="HI";const run=async(body:Record<string,unknown>,success:string)=>{setBusy(true);setMessage(null);try{await request(`/api/foundation/users/${userId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setMessage({type:"success",text:success});router.refresh()}catch(error){setMessage({type:"error",text:error instanceof Error?error.message:"Request failed"})}finally{setBusy(false)}};return <div className={styles.stack}><Message value={message}/><form className={styles.form} onSubmit={e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));void run({action:"profile",name:v.name,email:v.email},hi?"प्रोफ़ाइल सहेजी गई।":"Profile saved.")}}><label>{hi?"नाम":"Name"}<input name="name" defaultValue={user.name} disabled={!canManage}/></label><label>{hi?"ईमेल":"Email"}<input name="email" type="email" defaultValue={user.email} disabled={!canManage}/></label>{canManage&&<button className={styles.button} disabled={busy}>{hi?"प्रोफ़ाइल सहेजें":"Save profile"}</button>}</form>{canManage&&<section className={styles.card}><h3>{hi?"खाता स्थिति":"Account status"}</h3><p><span className={styles.badge}>{user.status}</span></p><div className={styles.formActions}>{user.status!=="ACTIVE"?<button className={styles.button} disabled={busy} onClick={()=>run({action:"status",status:"ACTIVE",reason:"Governed administrator reactivation"},hi?"खाता सक्रिय है।":"Account activated.")}>{hi?"सक्रिय करें":"Activate"}</button>:<button className={styles.button} disabled={busy} onClick={()=>confirm(hi?"क्या यह खाता निष्क्रिय करना है?":"Deactivate this account?")&&run({action:"status",status:"DISABLED",reason:"Governed administrator deactivation"},hi?"खाता निष्क्रिय है।":"Account deactivated.")}>{hi?"निष्क्रिय करें":"Deactivate"}</button>}</div></section>}{canManage&&(()=>{
  // Correction: an earlier pass in this session filtered "operationally conflicting" roles out of
  // this dropdown, assuming a person could only ever hold one primary role. That contradicted an
  // existing, already-approved test (__tests__/seera-block3/rbac-foundation.integration.test.ts,
  // "supports multiple roles and blocks duplicates") — holding more than one role (e.g. both
  // SALES_EXECUTIVE and RETAILER_USER) is intentional, tested behavior, not something to hide from
  // the picker. Reverted to the original, simpler "not already assigned" filter. The real P0 (a
  // multi-role user's login landing on the wrong portal) is fixed at its actual source instead —
  // portalLandingPathForRole() in portal-landing.ts now derives the landing portal from a single
  // deterministic primary role (oldest active assignment), independent of how many roles exist.
  const selectable=roles.filter(r=>!assignedRoleCodes.includes(r.code));
  return <section className={styles.card}><h3>{hi?"भूमिका असाइनमेंट":"Role assignments"}</h3>{assignedRoleCodes.length===0&&<p>{hi?"कोई भूमिका असाइन नहीं की गई।":"No role assigned yet."}</p>}<div className={styles.permissions}>{assignedRoleCodes.map(code=><span key={code} className={styles.badge} style={{display:"inline-flex",alignItems:"center",gap:8}}>{code} · {hi?"सक्रिय":"Active"}<button type="button" className={styles.secondary} style={{padding:"2px 8px",minHeight:"auto",border:0}} disabled={busy} onClick={()=>confirm(hi?`भूमिका हटाएं: ${code}?`:`Remove role: ${code}?`)&&run({action:"remove_role",roleCode:code,reason:"Governed administrator removal"},hi?"भूमिका हटाई गई।":"Role removed.")}>{hi?"हटाएं":"Remove"}</button></span>)}</div><form className={styles.form} onSubmit={e=>{e.preventDefault();const code=String(new FormData(e.currentTarget).get("roleCode"));void run({action:"assign_role",roleCode:code,reason:"Governed administrator assignment"},hi?"भूमिका असाइन की गई।":"Role assigned.")}}><label>{assignedRoleCodes.length>0?(hi?"अतिरिक्त भूमिका असाइन करें":"Assign additional role"):(hi?"भूमिका चुनें":"Choose a role")}<select name="roleCode">{selectable.map(r=><option key={r.code} value={r.code}>{r.name}</option>)}</select></label><button className={styles.button} disabled={busy||selectable.length===0}>{assignedRoleCodes.length>0?(hi?"अतिरिक्त भूमिका असाइन करें":"Assign additional role"):(hi?"भूमिका असाइन करें":"Assign role")}</button></form></section>
})()}</div>}
export function SettingsForm({flags,settings,canManage,language}:{flags:{key:string;enabled:boolean;description:string|null}[];settings:{key:string;value:unknown;version:number}[];canManage:boolean;language:"EN"|"HI"}){const router=useRouter(),[busy,setBusy]=useState(false),[message,setMessage]=useState<{type:"success"|"error";text:string}|null>(null),hi=language==="HI";const toggle=async(key:string,enabled:boolean)=>{if(!canManage||!confirm(hi?"इस नियंत्रित सुविधा को बदलें?":"Change this governed feature?"))return;setBusy(true);try{await request("/api/foundation/configuration",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"flag",key,enabled,reason:"Phase 1 governed settings workspace"})});setMessage({type:"success",text:hi?"सेटिंग सहेजी गई।":"Setting saved."});router.refresh()}catch(error){setMessage({type:"error",text:error instanceof Error?error.message:"Request failed"})}finally{setBusy(false)}};return <div className={styles.stack}><Message value={message}/><div className={styles.grid}>{flags.map(flag=><article className={styles.card} key={flag.key}><h3>{flag.key.replaceAll("."," · ")}</h3><p>{flag.description??(hi?"नियंत्रित पोर्टल सुविधा":"Governed portal capability")}</p><p><span className={styles.badge}>{flag.enabled?(hi?"सक्रिय":"Enabled"):(hi?"बंद":"Disabled")}</span></p>{canManage&&<button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>toggle(flag.key,!flag.enabled)}>{flag.enabled?(hi?"बंद करें":"Disable"):(hi?"सक्रिय करें":"Enable")}</button>}</article>)}</div><section className={styles.card}><h2>{hi?"अनुप्रयोग प्राथमिकताएँ":"Application preferences"}</h2>{settings.map(setting=><p key={setting.key}><strong>{setting.key}</strong><br/><span>{String(setting.value)} · v{setting.version}</span></p>)}</section></div>}
export function NotificationActions({id,language}:{id:string;language:"EN"|"HI"}){const router=useRouter(),[busy,setBusy]=useState(false);const update=async(action:"read"|"archive")=>{setBusy(true);try{await request("/api/foundation/notifications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({notificationId:id,action})});router.refresh()}finally{setBusy(false)}};return <div className={styles.formActions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>update("read")}>{language==="HI"?"पढ़ा हुआ":"Mark read"}</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>update("archive")}>{language==="HI"?"संग्रहित करें":"Archive"}</button></div>}
